$axure.loadCurrentPage({
  "url":"看红包广告.html",
  "generationDate":new Date(1448007541111.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"bohao"],
  "page":{
    "packageId":"5d12f85f59d64df8b34e9f17a393108b",
    "type":"Axure:Page",
    "name":"看红包广告",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9dfb62a2eebd4bb0b6e2ccbec099c0bf",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"93fd5d385bb2419698ca8d204db6bd4a"},
{
          "id":"31783725086c4f8397d21eaa8a45b070",
          "label":"guanggao",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":250,
              "height":431}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"fbaac41f038e41d0b7ccd80f1969d7f9",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"76da5292e9d545d6b6418a7179096d7d",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":18,
                      "y":40},
                    "size":{
                      "width":57,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"691c89dffb9b4150b22764fbdebe654f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":18,
                          "y":40},
                        "size":{
                          "width":57,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bd9ce3bd34b64c40963806eea7141ca5",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":66},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85b1bd1ab142406b9640e35be1f5e90a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":66},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"63c6a82cb608448b805e48122608776d",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":92},
                    "size":{
                      "width":250,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/index/u36_line.png"}},
{
                  "id":"9c8dfbe119df44318bc68b0b9b71f936",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":56},
                    "size":{
                      "width":200,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF777777}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/广告/u15_line.png"}},
{
                  "id":"e3d0320a34874cd3a03ea0d0a1d770b7",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":272},
                    "size":{
                      "width":250,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"72cfe9fb463e42bc8d550652a7248c75",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":272},
                        "size":{
                          "width":250,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/广告/u22.png"}},
{
                  "id":"4a72bfc7254540f49f7f11683d54dc5d",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":25,
                      "y":276},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"260a2b479c954f41a8344cc23fd63a21",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":25,
                          "y":276},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b2840ece48d447cd94ab896766c2b916",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":25,
                      "y":302},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"43a3640cb29e4132ab130e4fa65f4a56",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":25,
                          "y":302},
                        "size":{
                          "width":30,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/广告/u26.png"}},
{
                  "id":"14daf92a58624ba89f3798ae7eb5d450",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":65,
                      "y":299},
                    "size":{
                      "width":49,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"25caf652dc9a40d386013407195c6e50",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":65,
                          "y":299},
                        "size":{
                          "width":49,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c31cdf7171dc432796862abe49cefe2f",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":65,
                      "y":317},
                    "size":{
                      "width":49,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"60d7e16944194a038bdeca1fcf6de015",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":65,
                          "y":317},
                        "size":{
                          "width":49,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9dbe447d2d7f4a9097ad1e9fbcceffd1",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":25,
                      "y":331},
                    "size":{
                      "width":205,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF777777}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/广告/u32_line.png"}},
{
                  "id":"ebd519ca16ab443f933af9d5fcba8c23",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":25,
                      "y":342},
                    "size":{
                      "width":142,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"630cd7301dbe435ba090b5b00b1ce693",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":25,
                          "y":342},
                        "size":{
                          "width":142,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fdffa92ab11d4987a8c388f9e89a277a",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e277781d1314f168c1c0f1cacbe6ed7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"5f9f44a483b448a4b71851c75b18b8ac",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":98,
                      "y":7},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3962043c4fc34913bde5272eb3fab038",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":98,
                          "y":7},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0f5a414648ce4814852d13790fb7ba6c",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":7},
                    "size":{
                      "width":35,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4eba7db435e14051af86b22809d11882",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":7},
                        "size":{
                          "width":35,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 看红包",
                              "target":{
                                "targetType":"page",
                                "url":"看红包.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7941f192864e41428d0acb9bab045ba0",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":92},
                    "size":{
                      "width":250,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/index/u36_line.png"}},
{
                  "id":"9331a3127cff47899c3c3a05ca15977a",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":387.5},
                    "size":{
                      "width":250,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"02272c7a5879481cae40a680af920526",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":387.5},
                        "size":{
                          "width":250,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/底部1_u88.png"}},
{
                  "id":"f74d433baccc4c79b6c95987bc6fa864",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":392.5},
                    "size":{
                      "width":100,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e6856f2bfc2640488a43c7b4fcd5135b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":392.5},
                        "size":{
                          "width":100,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 +yibi 向上滑动 500 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["f6db27a428454a5e97779e6789875e68"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"slideUp",
                                      "duration":500,
                                      "showType":"none"}}}]},
{
                              "action":"wait",
                              "description":"等待700毫秒",
                              "waitTime":700},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 看红包",
                              "target":{
                                "targetType":"page",
                                "url":"看红包.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/商品页面2/u47.png"}},
{
                  "id":"f6db27a428454a5e97779e6789875e68",
                  "label":"+yibi",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":false,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":91,
                      "y":276},
                    "size":{
                      "width":68,
                      "height":28},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9399459e28243f39502e9c4e26a4124",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":91,
                          "y":276},
                        "size":{
                          "width":68,
                          "height":28},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b06753d01fe74b2088e8102ec7000eb9",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":112},
                    "size":{
                      "width":250,
                      "height":138}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7cd3207888274244a9dbe0b45b8b7a27",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":112},
                        "size":{
                          "width":250,
                          "height":138}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/看红包广告/u38.png"}},
{
                  "id":"32b2580c5b4d446f9caed7f788ac9847",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":86,
                      "y":149},
                    "size":{
                      "width":64,
                      "height":64}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c89824742d541dab8f89e4c81a347de",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":86,
                          "y":149},
                        "size":{
                          "width":64,
                          "height":64}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/看红包广告/u40.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"f37b191ee8854b198ecd8fbec269c24e",
          "label":"顶部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":40,
              "y":80},
            "size":{
              "width":250,
              "height":20},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f58e7c1ea9504a3a9a6b8f4310e733eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":40,
                  "y":80},
                "size":{
                  "width":250,
                  "height":20},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/顶部_u80.png"}},
{
          "id":"8cd05ef261fc449ea183802f8fe2424f",
          "label":"底部",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":530},
            "size":{
              "width":356,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f14af2b067124ce695d3134fbff1c608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":530},
                "size":{
                  "width":356,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u82.png"}},
{
          "id":"b866816cf5c2490dafab8c98f4103711",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":2},
            "size":{
              "width":327,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e568da55d7c430f9476f69865840f53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":2},
                "size":{
                  "width":327,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u84.png"}},
{
          "id":"91aa64d3be8b41099009ea362a428256",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":336,
              "height":2},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5533cd9fbea8468f8dcccd152ed4317b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":336,
                  "height":2},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u86.png"}}]}},
  "masters":{
    "93fd5d385bb2419698ca8d204db6bd4a":{
      "packageId":"93fd5d385bb2419698ca8d204db6bd4a",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2e194cf0c2b54c5680885a8df07da4e2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":336,
                "height":627}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0c76e3d052f04fcfb070a80a46e1e3f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":336,
                    "height":627}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u1.png"}},
{
            "id":"12b733eb02494e5a8662e96bcc215f5f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":100},
              "size":{
                "width":250,
                "height":430}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18c2b83789bc48f89e71a44ca19cb8ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":100},
                  "size":{
                    "width":250,
                    "height":430}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u3.png"}}]}}},
  "objectPaths":{
    "9dfb62a2eebd4bb0b6e2ccbec099c0bf":{
      "scriptId":"u0",
      "2e194cf0c2b54c5680885a8df07da4e2":{
        "scriptId":"u1"},
      "0c76e3d052f04fcfb070a80a46e1e3f9":{
        "scriptId":"u2"},
      "12b733eb02494e5a8662e96bcc215f5f":{
        "scriptId":"u3"},
      "18c2b83789bc48f89e71a44ca19cb8ae":{
        "scriptId":"u4"}},
    "31783725086c4f8397d21eaa8a45b070":{
      "scriptId":"u5"},
    "76da5292e9d545d6b6418a7179096d7d":{
      "scriptId":"u6"},
    "691c89dffb9b4150b22764fbdebe654f":{
      "scriptId":"u7"},
    "bd9ce3bd34b64c40963806eea7141ca5":{
      "scriptId":"u8"},
    "85b1bd1ab142406b9640e35be1f5e90a":{
      "scriptId":"u9"},
    "63c6a82cb608448b805e48122608776d":{
      "scriptId":"u10"},
    "9c8dfbe119df44318bc68b0b9b71f936":{
      "scriptId":"u11"},
    "e3d0320a34874cd3a03ea0d0a1d770b7":{
      "scriptId":"u12"},
    "72cfe9fb463e42bc8d550652a7248c75":{
      "scriptId":"u13"},
    "4a72bfc7254540f49f7f11683d54dc5d":{
      "scriptId":"u14"},
    "260a2b479c954f41a8344cc23fd63a21":{
      "scriptId":"u15"},
    "b2840ece48d447cd94ab896766c2b916":{
      "scriptId":"u16"},
    "43a3640cb29e4132ab130e4fa65f4a56":{
      "scriptId":"u17"},
    "14daf92a58624ba89f3798ae7eb5d450":{
      "scriptId":"u18"},
    "25caf652dc9a40d386013407195c6e50":{
      "scriptId":"u19"},
    "c31cdf7171dc432796862abe49cefe2f":{
      "scriptId":"u20"},
    "60d7e16944194a038bdeca1fcf6de015":{
      "scriptId":"u21"},
    "9dbe447d2d7f4a9097ad1e9fbcceffd1":{
      "scriptId":"u22"},
    "ebd519ca16ab443f933af9d5fcba8c23":{
      "scriptId":"u23"},
    "630cd7301dbe435ba090b5b00b1ce693":{
      "scriptId":"u24"},
    "fdffa92ab11d4987a8c388f9e89a277a":{
      "scriptId":"u25"},
    "7e277781d1314f168c1c0f1cacbe6ed7":{
      "scriptId":"u26"},
    "5f9f44a483b448a4b71851c75b18b8ac":{
      "scriptId":"u27"},
    "3962043c4fc34913bde5272eb3fab038":{
      "scriptId":"u28"},
    "0f5a414648ce4814852d13790fb7ba6c":{
      "scriptId":"u29"},
    "4eba7db435e14051af86b22809d11882":{
      "scriptId":"u30"},
    "7941f192864e41428d0acb9bab045ba0":{
      "scriptId":"u31"},
    "9331a3127cff47899c3c3a05ca15977a":{
      "scriptId":"u32"},
    "02272c7a5879481cae40a680af920526":{
      "scriptId":"u33"},
    "f74d433baccc4c79b6c95987bc6fa864":{
      "scriptId":"u34"},
    "e6856f2bfc2640488a43c7b4fcd5135b":{
      "scriptId":"u35"},
    "f6db27a428454a5e97779e6789875e68":{
      "scriptId":"u36"},
    "e9399459e28243f39502e9c4e26a4124":{
      "scriptId":"u37"},
    "b06753d01fe74b2088e8102ec7000eb9":{
      "scriptId":"u38"},
    "7cd3207888274244a9dbe0b45b8b7a27":{
      "scriptId":"u39"},
    "32b2580c5b4d446f9caed7f788ac9847":{
      "scriptId":"u40"},
    "2c89824742d541dab8f89e4c81a347de":{
      "scriptId":"u41"},
    "f37b191ee8854b198ecd8fbec269c24e":{
      "scriptId":"u42"},
    "f58e7c1ea9504a3a9a6b8f4310e733eb":{
      "scriptId":"u43"},
    "8cd05ef261fc449ea183802f8fe2424f":{
      "scriptId":"u44"},
    "f14af2b067124ce695d3134fbff1c608":{
      "scriptId":"u45"},
    "b866816cf5c2490dafab8c98f4103711":{
      "scriptId":"u46"},
    "5e568da55d7c430f9476f69865840f53":{
      "scriptId":"u47"},
    "91aa64d3be8b41099009ea362a428256":{
      "scriptId":"u48"},
    "5533cd9fbea8468f8dcccd152ed4317b":{
      "scriptId":"u49"}}});