$axure.loadCurrentPage({
  "url":"抢红包广告.html",
  "generationDate":new Date(1448007541005.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"bohao"],
  "page":{
    "packageId":"3df3b90a342a40069aff96448da2502a",
    "type":"Axure:Page",
    "name":"抢红包广告",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9dfb62a2eebd4bb0b6e2ccbec099c0bf",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"93fd5d385bb2419698ca8d204db6bd4a"},
{
          "id":"31783725086c4f8397d21eaa8a45b070",
          "label":"guanggao",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":250,
              "height":730}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"拖动限制<br> (If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 guanggao 纵向拖动",
                      "objectsToMoves":[{
                          "objectPath":["31783725086c4f8397d21eaa8a45b070"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]},
{
                  "description":"向下拖动<br> (If area of guanggao 未接触 area of 顶部)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["31783725086c4f8397d21eaa8a45b070"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["f37b191ee8854b198ecd8fbec269c24e"]}]}]},
                  "actions":[{
                      "action":"wait",
                      "description":"等待50毫秒",
                      "waitTime":50},
{
                      "action":"moveWidget",
                      "description":"移动 guanggao 到 (40,100)",
                      "objectsToMoves":[{
                          "objectPath":["31783725086c4f8397d21eaa8a45b070"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"40",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"100",
                              "stos":[]},
                            "options":{
}}}]}]},
{
                  "description":"向上拖动<br> (If area of guanggao 未接触 area of 底部)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["31783725086c4f8397d21eaa8a45b070"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["8cd05ef261fc449ea183802f8fe2424f"]}]}]},
                  "actions":[{
                      "action":"wait",
                      "description":"等待50毫秒",
                      "waitTime":50},
{
                      "action":"moveWidget",
                      "description":"移动 guanggao 到 (40,-190)",
                      "objectsToMoves":[{
                          "objectPath":["31783725086c4f8397d21eaa8a45b070"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"40",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"-190",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"fbaac41f038e41d0b7ccd80f1969d7f9",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bd15ba6efd894072a5299d3b497badcc",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":250,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5bf3052d4ae242209a33be8db69bdb37",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":250,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/捡易币/u12.png"}},
{
                  "id":"0eefa1ee5d8f451398068e016a9c1d73",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88,
                      "y":66},
                    "size":{
                      "width":73,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd0688093c45476f8d4b823b7826e556",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88,
                          "y":66},
                        "size":{
                          "width":73,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"76da5292e9d545d6b6418a7179096d7d",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":18,
                      "y":140},
                    "size":{
                      "width":57,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"691c89dffb9b4150b22764fbdebe654f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":18,
                          "y":140},
                        "size":{
                          "width":57,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bd9ce3bd34b64c40963806eea7141ca5",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":166},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85b1bd1ab142406b9640e35be1f5e90a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":166},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"63c6a82cb608448b805e48122608776d",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":192},
                    "size":{
                      "width":250,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/index/u36_line.png"}},
{
                  "id":"9c8dfbe119df44318bc68b0b9b71f936",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":156},
                    "size":{
                      "width":200,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF777777}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/广告/u15_line.png"}},
{
                  "id":"26e04c7809d247f7ad1dec87ecb6c109",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":220},
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9ca196d1e8e24031ac6451ba4d3dbada",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":220},
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"8e9e4c4cd79443b4bf77247d52fa30fd",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":228},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"97529c9070174fd1b77f54aa2eddbac8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":228},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8a935717647548f2885d8a343e0d9088",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":260},
                    "size":{
                      "width":250,
                      "height":150}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b311e8d381ec4e04b214712a923b35b6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":260},
                        "size":{
                          "width":250,
                          "height":150}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/广告/u20.png"}},
{
                  "id":"e3d0320a34874cd3a03ea0d0a1d770b7",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":430},
                    "size":{
                      "width":250,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"72cfe9fb463e42bc8d550652a7248c75",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":430},
                        "size":{
                          "width":250,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/广告/u22.png"}},
{
                  "id":"4a72bfc7254540f49f7f11683d54dc5d",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":433},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"260a2b479c954f41a8344cc23fd63a21",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":433},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b2840ece48d447cd94ab896766c2b916",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":459},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"43a3640cb29e4132ab130e4fa65f4a56",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":459},
                        "size":{
                          "width":30,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/广告/u26.png"}},
{
                  "id":"14daf92a58624ba89f3798ae7eb5d450",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":58,
                      "y":456},
                    "size":{
                      "width":49,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"25caf652dc9a40d386013407195c6e50",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":58,
                          "y":456},
                        "size":{
                          "width":49,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c31cdf7171dc432796862abe49cefe2f",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":58,
                      "y":474},
                    "size":{
                      "width":49,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"60d7e16944194a038bdeca1fcf6de015",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":58,
                          "y":474},
                        "size":{
                          "width":49,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9dbe447d2d7f4a9097ad1e9fbcceffd1",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":25,
                      "y":489},
                    "size":{
                      "width":205,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF777777}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/广告/u32_line.png"}},
{
                  "id":"ebd519ca16ab443f933af9d5fcba8c23",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":18,
                      "y":499},
                    "size":{
                      "width":142,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"630cd7301dbe435ba090b5b00b1ce693",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":18,
                          "y":499},
                        "size":{
                          "width":142,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fdffa92ab11d4987a8c388f9e89a277a",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e277781d1314f168c1c0f1cacbe6ed7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"5f9f44a483b448a4b71851c75b18b8ac",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":98,
                      "y":7},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3962043c4fc34913bde5272eb3fab038",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":98,
                          "y":7},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0f5a414648ce4814852d13790fb7ba6c",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":7},
                    "size":{
                      "width":35,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4eba7db435e14051af86b22809d11882",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":7},
                        "size":{
                          "width":35,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 捡易币",
                              "target":{
                                "targetType":"page",
                                "url":"捡易币.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"360671cccfd04daeb95fe48a9d1d9b36",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":550},
                    "size":{
                      "width":250,
                      "height":170}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f9ffe11e3a50475f9fd84e8346f1b337",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":550},
                        "size":{
                          "width":250,
                          "height":170}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/抢红包广告/u41.png"}},
{
                  "id":"52685547893b4496ad1abf5fa0e15edb",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":560},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"96dd91217bec4fb4b92b311ec9630d28",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":560},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"19d5f88376584a5e9451a3fe827f0110",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "location":{
                      "x":68,
                      "y":585},
                    "size":{
                      "width":43,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"afa0690664de4b1b8208f4183a111b8d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "location":{
                          "x":68,
                          "y":585},
                        "size":{
                          "width":43,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4a040550a2bd455198d6f164c1722425",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"11px",
                    "location":{
                      "x":118,
                      "y":588},
                    "size":{
                      "width":50,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"121d0450725143efabeac8039ca3a7fc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"11px",
                        "location":{
                          "x":118,
                          "y":588},
                        "size":{
                          "width":50,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3c02834753554559baefbaf51d26bf8e",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "location":{
                      "x":42,
                      "y":609},
                    "size":{
                      "width":151,
                      "height":13}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6957095f220143c6ba2c2202c9ad2195",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "location":{
                          "x":42,
                          "y":609},
                        "size":{
                          "width":151,
                          "height":13}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b2e62ef03af14730ba5710c0533c5dd2",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF6600,
                      "opacity":1},
                    "location":{
                      "x":67,
                      "y":627},
                    "size":{
                      "width":111,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"84e1a34cd6114b1793a051af845663e5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF6600,
                          "opacity":1},
                        "location":{
                          "x":67,
                          "y":627},
                        "size":{
                          "width":111,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"79ca56814e4c4ab3b283bd00e5487b64",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":72,
                      "y":642},
                    "size":{
                      "width":100,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0f0e0f3b749f4ee783f455fd80f4623d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":72,
                          "y":642},
                        "size":{
                          "width":100,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/抢红包广告/u53.png"}},
{
                  "id":"f36ec232251a414faf16c36fbfc8bf9a",
                  "label":"text",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "hint":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1}}},
                    "location":{
                      "x":74,
                      "y":645},
                    "size":{
                      "width":96,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "placeholderText":"输入核心广告词"},
{
                  "id":"df0c0cfad99f4d1b8c9cec4ebab55bcd",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":67.5,
                      "y":680},
                    "size":{
                      "width":115,
                      "height":20},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"76d7a9502c5644ef969e2b167a5fe022",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":67.5,
                          "y":680},
                        "size":{
                          "width":115,
                          "height":20},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1<br> (If 文字于 text = &quot;广告词&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["f36ec232251a414faf16c36fbfc8bf9a"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"广告词",
                              "stos":[]}},
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 +yibi 向上滑动 500 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["669efd2483974c38bcde25f263f69ca3"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"slideUp",
                                      "duration":500,
                                      "showType":"none"}}}]},
{
                              "action":"wait",
                              "description":"等待700毫秒",
                              "waitTime":700},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 抢红包",
                              "target":{
                                "targetType":"page",
                                "url":"抢红包.html",
                                "includeVariables":true},
                              "linkType":"current"}]},
{
                          "description":"用例 2<br> (Else If 文字于 text ≠ &quot;广告词&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"!=",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["f36ec232251a414faf16c36fbfc8bf9a"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"广告词",
                              "stos":[]}},
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 不对提示 淡入淡出 500 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["46570d8919504eb497f2866353262dcc"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"fade",
                                      "duration":500,
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 不对提示 淡入淡出 500 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["46570d8919504eb497f2866353262dcc"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/抢红包广告/u56.png"}},
{
                  "id":"46570d8919504eb497f2866353262dcc",
                  "label":"不对提示",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "location":{
                      "x":25,
                      "y":555},
                    "size":{
                      "width":200,
                      "height":30},
                    "visible":false,
                    "cornerRadiusTopLeft":"9"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e3c6a2bbcf6e452d9cf894806837bfe3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "location":{
                          "x":25,
                          "y":555},
                        "size":{
                          "width":200,
                          "height":30},
                        "visible":false,
                        "cornerRadiusTopLeft":"9"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/抢红包广告/不对提示_u58.png"}},
{
                  "id":"669efd2483974c38bcde25f263f69ca3",
                  "label":"+yibi",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":false,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":67,
                      "y":540},
                    "size":{
                      "width":116,
                      "height":28},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5ede29904e8243afb05de402d7112904",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":67,
                          "y":540},
                        "size":{
                          "width":116,
                          "height":28},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"f37b191ee8854b198ecd8fbec269c24e",
          "label":"顶部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":40,
              "y":80},
            "size":{
              "width":250,
              "height":20},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f58e7c1ea9504a3a9a6b8f4310e733eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":40,
                  "y":80},
                "size":{
                  "width":250,
                  "height":20},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/顶部_u80.png"}},
{
          "id":"8cd05ef261fc449ea183802f8fe2424f",
          "label":"底部",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":530},
            "size":{
              "width":356,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f14af2b067124ce695d3134fbff1c608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":530},
                "size":{
                  "width":356,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u82.png"}},
{
          "id":"b866816cf5c2490dafab8c98f4103711",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":2},
            "size":{
              "width":327,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e568da55d7c430f9476f69865840f53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":2},
                "size":{
                  "width":327,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u84.png"}},
{
          "id":"91aa64d3be8b41099009ea362a428256",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":336,
              "height":2},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5533cd9fbea8468f8dcccd152ed4317b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":336,
                  "height":2},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u86.png"}},
{
          "id":"b5d53bac46b14b5daf9e631ce7e9e7cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":790},
            "size":{
              "width":320,
              "height":70},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e57685d6a6a04b5b9442d88cbb57de3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":790},
                "size":{
                  "width":320,
                  "height":70},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/抢红包广告/u70.png"}}]}},
  "masters":{
    "93fd5d385bb2419698ca8d204db6bd4a":{
      "packageId":"93fd5d385bb2419698ca8d204db6bd4a",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2e194cf0c2b54c5680885a8df07da4e2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":336,
                "height":627}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0c76e3d052f04fcfb070a80a46e1e3f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":336,
                    "height":627}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u1.png"}},
{
            "id":"12b733eb02494e5a8662e96bcc215f5f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":100},
              "size":{
                "width":250,
                "height":430}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18c2b83789bc48f89e71a44ca19cb8ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":100},
                  "size":{
                    "width":250,
                    "height":430}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u3.png"}}]}}},
  "objectPaths":{
    "9dfb62a2eebd4bb0b6e2ccbec099c0bf":{
      "scriptId":"u0",
      "2e194cf0c2b54c5680885a8df07da4e2":{
        "scriptId":"u1"},
      "0c76e3d052f04fcfb070a80a46e1e3f9":{
        "scriptId":"u2"},
      "12b733eb02494e5a8662e96bcc215f5f":{
        "scriptId":"u3"},
      "18c2b83789bc48f89e71a44ca19cb8ae":{
        "scriptId":"u4"}},
    "31783725086c4f8397d21eaa8a45b070":{
      "scriptId":"u5"},
    "bd15ba6efd894072a5299d3b497badcc":{
      "scriptId":"u6"},
    "5bf3052d4ae242209a33be8db69bdb37":{
      "scriptId":"u7"},
    "0eefa1ee5d8f451398068e016a9c1d73":{
      "scriptId":"u8"},
    "cd0688093c45476f8d4b823b7826e556":{
      "scriptId":"u9"},
    "76da5292e9d545d6b6418a7179096d7d":{
      "scriptId":"u10"},
    "691c89dffb9b4150b22764fbdebe654f":{
      "scriptId":"u11"},
    "bd9ce3bd34b64c40963806eea7141ca5":{
      "scriptId":"u12"},
    "85b1bd1ab142406b9640e35be1f5e90a":{
      "scriptId":"u13"},
    "63c6a82cb608448b805e48122608776d":{
      "scriptId":"u14"},
    "9c8dfbe119df44318bc68b0b9b71f936":{
      "scriptId":"u15"},
    "26e04c7809d247f7ad1dec87ecb6c109":{
      "scriptId":"u16"},
    "9ca196d1e8e24031ac6451ba4d3dbada":{
      "scriptId":"u17"},
    "8e9e4c4cd79443b4bf77247d52fa30fd":{
      "scriptId":"u18"},
    "97529c9070174fd1b77f54aa2eddbac8":{
      "scriptId":"u19"},
    "8a935717647548f2885d8a343e0d9088":{
      "scriptId":"u20"},
    "b311e8d381ec4e04b214712a923b35b6":{
      "scriptId":"u21"},
    "e3d0320a34874cd3a03ea0d0a1d770b7":{
      "scriptId":"u22"},
    "72cfe9fb463e42bc8d550652a7248c75":{
      "scriptId":"u23"},
    "4a72bfc7254540f49f7f11683d54dc5d":{
      "scriptId":"u24"},
    "260a2b479c954f41a8344cc23fd63a21":{
      "scriptId":"u25"},
    "b2840ece48d447cd94ab896766c2b916":{
      "scriptId":"u26"},
    "43a3640cb29e4132ab130e4fa65f4a56":{
      "scriptId":"u27"},
    "14daf92a58624ba89f3798ae7eb5d450":{
      "scriptId":"u28"},
    "25caf652dc9a40d386013407195c6e50":{
      "scriptId":"u29"},
    "c31cdf7171dc432796862abe49cefe2f":{
      "scriptId":"u30"},
    "60d7e16944194a038bdeca1fcf6de015":{
      "scriptId":"u31"},
    "9dbe447d2d7f4a9097ad1e9fbcceffd1":{
      "scriptId":"u32"},
    "ebd519ca16ab443f933af9d5fcba8c23":{
      "scriptId":"u33"},
    "630cd7301dbe435ba090b5b00b1ce693":{
      "scriptId":"u34"},
    "fdffa92ab11d4987a8c388f9e89a277a":{
      "scriptId":"u35"},
    "7e277781d1314f168c1c0f1cacbe6ed7":{
      "scriptId":"u36"},
    "5f9f44a483b448a4b71851c75b18b8ac":{
      "scriptId":"u37"},
    "3962043c4fc34913bde5272eb3fab038":{
      "scriptId":"u38"},
    "0f5a414648ce4814852d13790fb7ba6c":{
      "scriptId":"u39"},
    "4eba7db435e14051af86b22809d11882":{
      "scriptId":"u40"},
    "360671cccfd04daeb95fe48a9d1d9b36":{
      "scriptId":"u41"},
    "f9ffe11e3a50475f9fd84e8346f1b337":{
      "scriptId":"u42"},
    "52685547893b4496ad1abf5fa0e15edb":{
      "scriptId":"u43"},
    "96dd91217bec4fb4b92b311ec9630d28":{
      "scriptId":"u44"},
    "19d5f88376584a5e9451a3fe827f0110":{
      "scriptId":"u45"},
    "afa0690664de4b1b8208f4183a111b8d":{
      "scriptId":"u46"},
    "4a040550a2bd455198d6f164c1722425":{
      "scriptId":"u47"},
    "121d0450725143efabeac8039ca3a7fc":{
      "scriptId":"u48"},
    "3c02834753554559baefbaf51d26bf8e":{
      "scriptId":"u49"},
    "6957095f220143c6ba2c2202c9ad2195":{
      "scriptId":"u50"},
    "b2e62ef03af14730ba5710c0533c5dd2":{
      "scriptId":"u51"},
    "84e1a34cd6114b1793a051af845663e5":{
      "scriptId":"u52"},
    "79ca56814e4c4ab3b283bd00e5487b64":{
      "scriptId":"u53"},
    "0f0e0f3b749f4ee783f455fd80f4623d":{
      "scriptId":"u54"},
    "f36ec232251a414faf16c36fbfc8bf9a":{
      "scriptId":"u55"},
    "df0c0cfad99f4d1b8c9cec4ebab55bcd":{
      "scriptId":"u56"},
    "76d7a9502c5644ef969e2b167a5fe022":{
      "scriptId":"u57"},
    "46570d8919504eb497f2866353262dcc":{
      "scriptId":"u58"},
    "e3c6a2bbcf6e452d9cf894806837bfe3":{
      "scriptId":"u59"},
    "669efd2483974c38bcde25f263f69ca3":{
      "scriptId":"u60"},
    "5ede29904e8243afb05de402d7112904":{
      "scriptId":"u61"},
    "f37b191ee8854b198ecd8fbec269c24e":{
      "scriptId":"u62"},
    "f58e7c1ea9504a3a9a6b8f4310e733eb":{
      "scriptId":"u63"},
    "8cd05ef261fc449ea183802f8fe2424f":{
      "scriptId":"u64"},
    "f14af2b067124ce695d3134fbff1c608":{
      "scriptId":"u65"},
    "b866816cf5c2490dafab8c98f4103711":{
      "scriptId":"u66"},
    "5e568da55d7c430f9476f69865840f53":{
      "scriptId":"u67"},
    "91aa64d3be8b41099009ea362a428256":{
      "scriptId":"u68"},
    "5533cd9fbea8468f8dcccd152ed4317b":{
      "scriptId":"u69"},
    "b5d53bac46b14b5daf9e631ce7e9e7cd":{
      "scriptId":"u70"},
    "e57685d6a6a04b5b9442d88cbb57de3c":{
      "scriptId":"u71"}}});