$axure.loadCurrentPage({
  "url":"易电话.html",
  "generationDate":new Date(1448007540422.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"bohao"],
  "page":{
    "packageId":"354658bd3c0746d9b53fdae4a34551c8",
    "type":"Axure:Page",
    "name":"易电话",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"548b40a3e1ee4b8f96ba6c7422d34545",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"93fd5d385bb2419698ca8d204db6bd4a"},
{
          "id":"f6c1275ea216431f81ca2b816f2cabe4",
          "label":"dianhua",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":250,
              "height":390}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"ca71d950ce614f46924927961bff9000",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4f1df17cd4b24109b8b053281c447ffc",
                  "label":"",
                  "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f1fef5810a584fcaa54445db7e8fc17a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"dc6192f6fdf94a038b09c3031dc67531",
                  "label":"",
                  "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":98,
                      "y":7},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"42f03becee3b41bba5a1b73e21cd29c1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":98,
                          "y":7},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0934f41f81634584b8e790c7ca71db57",
                  "label":"",
                  "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                  "panelIndex":0,
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":190},
                    "size":{
                      "width":250,
                      "height":200}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d6e3527389554618b76e0a762aa3d52d",
                      "label":"1",
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "size":{
                          "width":83,
                          "height":50}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"898abf23226f495ea1bc6efa175bdce2",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                          "panelIndex":0,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "size":{
                              "width":83,
                              "height":50}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"setFunction",
                                  "description":"设置 文字于 phone_number = &quot;[[target.text]][[this.text]]&quot;",
                                  "expr":{
                                    "exprType":"block",
                                    "subExprs":[{
                                        "exprType":"fcall",
                                        "functionName":"SetWidgetRichText",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["207f09878c3b45f5b409d94d844951ca"]},
{
                                            "exprType":"stringLiteral",
                                            "value":"[[target.text]][[this.text]]",
                                            "stos":[{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"target"},
                                                "prop":"text"},
{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"this"},
                                                "prop":"text"}]},
{
                                            "exprType":"booleanLiteral",
                                            "value":true}]}]}}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/易电话/1_u11.png"}},
{
                      "id":"f3a255c836b54238bfb310f347d501c1",
                      "label":"4",
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":0,
                          "y":50},
                        "size":{
                          "width":83,
                          "height":50}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"f5597e0f027f41dc82026bdc075a9a45",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                          "panelIndex":0,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":0,
                              "y":50},
                            "size":{
                              "width":83,
                              "height":50}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"setFunction",
                                  "description":"设置 文字于 phone_number = &quot;[[target.text]][[this.text]]&quot;",
                                  "expr":{
                                    "exprType":"block",
                                    "subExprs":[{
                                        "exprType":"fcall",
                                        "functionName":"SetWidgetRichText",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["207f09878c3b45f5b409d94d844951ca"]},
{
                                            "exprType":"stringLiteral",
                                            "value":"[[target.text]][[this.text]]",
                                            "stos":[{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"target"},
                                                "prop":"text"},
{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"this"},
                                                "prop":"text"}]},
{
                                            "exprType":"booleanLiteral",
                                            "value":true}]}]}}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/易电话/1_u11.png"}},
{
                      "id":"51f9864c76ea4729a91e8e4582f9aceb",
                      "label":"7",
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":0,
                          "y":100},
                        "size":{
                          "width":83,
                          "height":50}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e7972a464fbf4b24991826ff3f7ae4be",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                          "panelIndex":0,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":0,
                              "y":100},
                            "size":{
                              "width":83,
                              "height":50}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"setFunction",
                                  "description":"设置 文字于 phone_number = &quot;[[target.text]][[this.text]]&quot;",
                                  "expr":{
                                    "exprType":"block",
                                    "subExprs":[{
                                        "exprType":"fcall",
                                        "functionName":"SetWidgetRichText",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["207f09878c3b45f5b409d94d844951ca"]},
{
                                            "exprType":"stringLiteral",
                                            "value":"[[target.text]][[this.text]]",
                                            "stos":[{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"target"},
                                                "prop":"text"},
{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"this"},
                                                "prop":"text"}]},
{
                                            "exprType":"booleanLiteral",
                                            "value":true}]}]}}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/易电话/1_u11.png"}},
{
                      "id":"6a0103803f5547cdb2ee3c9801b4cca0",
                      "label":"2",
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":83,
                          "y":0},
                        "size":{
                          "width":83,
                          "height":50}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ce1a107e20a94b07bf35911cdab209a4",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                          "panelIndex":0,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":83,
                              "y":0},
                            "size":{
                              "width":83,
                              "height":50}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"setFunction",
                                  "description":"设置 文字于 phone_number = &quot;[[target.text]][[this.text]]&quot;",
                                  "expr":{
                                    "exprType":"block",
                                    "subExprs":[{
                                        "exprType":"fcall",
                                        "functionName":"SetWidgetRichText",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["207f09878c3b45f5b409d94d844951ca"]},
{
                                            "exprType":"stringLiteral",
                                            "value":"[[target.text]][[this.text]]",
                                            "stos":[{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"target"},
                                                "prop":"text"},
{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"this"},
                                                "prop":"text"}]},
{
                                            "exprType":"booleanLiteral",
                                            "value":true}]}]}}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/易电话/1_u11.png"}},
{
                      "id":"424bdb07ee2d48ccbc7758c4add17b08",
                      "label":"5",
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":83,
                          "y":50},
                        "size":{
                          "width":83,
                          "height":50}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"516ecf1bf70e498c94fe76e80b0dc659",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                          "panelIndex":0,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":83,
                              "y":50},
                            "size":{
                              "width":83,
                              "height":50}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"setFunction",
                                  "description":"设置 文字于 phone_number = &quot;[[target.text]][[this.text]]&quot;",
                                  "expr":{
                                    "exprType":"block",
                                    "subExprs":[{
                                        "exprType":"fcall",
                                        "functionName":"SetWidgetRichText",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["207f09878c3b45f5b409d94d844951ca"]},
{
                                            "exprType":"stringLiteral",
                                            "value":"[[target.text]][[this.text]]",
                                            "stos":[{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"target"},
                                                "prop":"text"},
{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"this"},
                                                "prop":"text"}]},
{
                                            "exprType":"booleanLiteral",
                                            "value":true}]}]}}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/易电话/1_u11.png"}},
{
                      "id":"e946d68ebfe249c6abc7279d057b2904",
                      "label":"8",
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":83,
                          "y":100},
                        "size":{
                          "width":83,
                          "height":50}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"2adfdc5df7e1479ea662be9618759ef5",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                          "panelIndex":0,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":83,
                              "y":100},
                            "size":{
                              "width":83,
                              "height":50}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"setFunction",
                                  "description":"设置 文字于 phone_number = &quot;[[target.text]][[this.text]]&quot;",
                                  "expr":{
                                    "exprType":"block",
                                    "subExprs":[{
                                        "exprType":"fcall",
                                        "functionName":"SetWidgetRichText",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["207f09878c3b45f5b409d94d844951ca"]},
{
                                            "exprType":"stringLiteral",
                                            "value":"[[target.text]][[this.text]]",
                                            "stos":[{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"target"},
                                                "prop":"text"},
{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"this"},
                                                "prop":"text"}]},
{
                                            "exprType":"booleanLiteral",
                                            "value":true}]}]}}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/易电话/1_u11.png"}},
{
                      "id":"13566f9af1c2489cad6f637ca6a92189",
                      "label":"3",
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":166,
                          "y":0},
                        "size":{
                          "width":84,
                          "height":50}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"12e7f391fa654ad0a81ef94631c8ba4a",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                          "panelIndex":0,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":166,
                              "y":0},
                            "size":{
                              "width":84,
                              "height":50}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"setFunction",
                                  "description":"设置 文字于 phone_number = &quot;[[target.text]][[this.text]]&quot;",
                                  "expr":{
                                    "exprType":"block",
                                    "subExprs":[{
                                        "exprType":"fcall",
                                        "functionName":"SetWidgetRichText",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["207f09878c3b45f5b409d94d844951ca"]},
{
                                            "exprType":"stringLiteral",
                                            "value":"[[target.text]][[this.text]]",
                                            "stos":[{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"target"},
                                                "prop":"text"},
{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"this"},
                                                "prop":"text"}]},
{
                                            "exprType":"booleanLiteral",
                                            "value":true}]}]}}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/易电话/3_u15.png"}},
{
                      "id":"ee89e1ef955f463ab8a7de3dc1114759",
                      "label":"6",
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":166,
                          "y":50},
                        "size":{
                          "width":84,
                          "height":50}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"0ab172b119364405946d249e88e633ce",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                          "panelIndex":0,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":166,
                              "y":50},
                            "size":{
                              "width":84,
                              "height":50}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"setFunction",
                                  "description":"设置 文字于 phone_number = &quot;[[target.text]][[this.text]]&quot;",
                                  "expr":{
                                    "exprType":"block",
                                    "subExprs":[{
                                        "exprType":"fcall",
                                        "functionName":"SetWidgetRichText",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["207f09878c3b45f5b409d94d844951ca"]},
{
                                            "exprType":"stringLiteral",
                                            "value":"[[target.text]][[this.text]]",
                                            "stos":[{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"target"},
                                                "prop":"text"},
{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"this"},
                                                "prop":"text"}]},
{
                                            "exprType":"booleanLiteral",
                                            "value":true}]}]}}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/易电话/3_u15.png"}},
{
                      "id":"af67db9547364d7184664c6292d196dd",
                      "label":"9",
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":166,
                          "y":100},
                        "size":{
                          "width":84,
                          "height":50}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"9c83bf7e296f421c9761866d4cc9cbb6",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                          "panelIndex":0,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":166,
                              "y":100},
                            "size":{
                              "width":84,
                              "height":50}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"setFunction",
                                  "description":"设置 文字于 phone_number = &quot;[[target.text]][[this.text]]&quot;",
                                  "expr":{
                                    "exprType":"block",
                                    "subExprs":[{
                                        "exprType":"fcall",
                                        "functionName":"SetWidgetRichText",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["207f09878c3b45f5b409d94d844951ca"]},
{
                                            "exprType":"stringLiteral",
                                            "value":"[[target.text]][[this.text]]",
                                            "stos":[{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"target"},
                                                "prop":"text"},
{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"this"},
                                                "prop":"text"}]},
{
                                            "exprType":"booleanLiteral",
                                            "value":true}]}]}}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/易电话/3_u15.png"}},
{
                      "id":"bc79252bcaff4dd18ceccd994b851fb3",
                      "label":"cha",
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":0,
                          "y":150},
                        "size":{
                          "width":83,
                          "height":50}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"178c0650ddb9472e843a9476e8d53902",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                          "panelIndex":0,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":0,
                              "y":150},
                            "size":{
                              "width":83,
                              "height":50}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/易电话/cha_u29.png"}},
{
                      "id":"8e24c8124800409b92a3c48b54df423c",
                      "label":"0",
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":83,
                          "y":150},
                        "size":{
                          "width":83,
                          "height":50}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c8425a2d86f146b1a3f063c3f4ea7f83",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                          "panelIndex":0,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":83,
                              "y":150},
                            "size":{
                              "width":83,
                              "height":50}},
                          "adaptiveStyles":{
}}],
                      "interactionMap":{
                        "onClick":{
                          "description":"OnClick",
                          "cases":[{
                              "description":"用例 1",
                              "isNewIfGroup":false,
                              "actions":[{
                                  "action":"setFunction",
                                  "description":"设置 文字于 phone_number = &quot;[[target.text]][[this.text]]&quot;",
                                  "expr":{
                                    "exprType":"block",
                                    "subExprs":[{
                                        "exprType":"fcall",
                                        "functionName":"SetWidgetRichText",
                                        "arguments":[{
                                            "exprType":"pathLiteral",
                                            "isThis":false,
                                            "isFocused":false,
                                            "isTarget":false,
                                            "value":["207f09878c3b45f5b409d94d844951ca"]},
{
                                            "exprType":"stringLiteral",
                                            "value":"[[target.text]][[this.text]]",
                                            "stos":[{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"target"},
                                                "prop":"text"},
{
                                                "computedType":"string",
                                                "sto":"propCall",
                                                "thisSTO":{
                                                  "desiredType":"widget",
                                                  "sto":"var",
                                                  "name":"this"},
                                                "prop":"text"}]},
{
                                            "exprType":"booleanLiteral",
                                            "value":true}]}]}}]}]}},
                      "tabbable":true,
                      "images":{
                        "normal~":"images/易电话/cha_u29.png"}},
{
                      "id":"7813f8c8da2d4502b808a67a0de209bd",
                      "label":"tonghua",
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":166,
                          "y":150},
                        "size":{
                          "width":84,
                          "height":50}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"3ebc00a4c56a44248fded9e5a0a74593",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                          "panelIndex":0,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":166,
                              "y":150},
                            "size":{
                              "width":84,
                              "height":50}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/易电话/tonghua_u33.png"}}]},
{
                  "id":"db48e7189bfb4c728b535dbe5d045e6b",
                  "label":"",
                  "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":25,
                      "y":348},
                    "size":{
                      "width":32,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2161da881be44169bd82aad4e85b2cc7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":25,
                          "y":348},
                        "size":{
                          "width":32,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/易电话/u35.png"}},
{
                  "id":"1826f5254dba4d2388ff781eece4a60b",
                  "label":"",
                  "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":194,
                      "y":348},
                    "size":{
                      "width":32,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0ea5bb02ce724c39b5de0aa5a49e65ec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":194,
                          "y":348},
                        "size":{
                          "width":32,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/易电话/u37.png"}},
{
                  "id":"6a7cfa9cfc384c94847e2d21d839ba09",
                  "label":"",
                  "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":160},
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ce67f494241a457cb71fc7aa0f5fd463",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"b19857ef79f7499e810615b566cc535b",
                  "label":"",
                  "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":14,
                      "y":167},
                    "size":{
                      "width":104,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"19a2d09d338f40fb8fc23fc5448e9cc0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":14,
                          "y":167},
                        "size":{
                          "width":104,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d3a492105524431ba56190bedc853849",
                  "label":"",
                  "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":176,
                      "y":165},
                    "size":{
                      "width":50,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF0101},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"62caf63435894f0db44ee5fdf5d1c4c4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":176,
                          "y":165},
                        "size":{
                          "width":50,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF0101},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/易电话/u43.png"}},
{
                  "id":"53bbd6cd715c472b98d217b65f58e4d8",
                  "label":"",
                  "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":2,
                      "y":339},
                    "size":{
                      "width":80,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 文字于 phone_number = &quot;[[target.text.substr(0,targ...&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["207f09878c3b45f5b409d94d844951ca"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"[[target.text.substr(0,target.text.length-1)]]",
                                        "localVariables":{
},
                                        "stos":[{
                                            "computedType":"string",
                                            "sto":"fCall",
                                            "thisSTO":{
                                              "computedType":"string",
                                              "desiredType":"string",
                                              "sto":"propCall",
                                              "thisSTO":{
                                                "desiredType":"widget",
                                                "sto":"var",
                                                "name":"target"},
                                              "prop":"text"},
                                            "func":"substr",
                                            "arguments":[{
                                                "computedType":"int",
                                                "sto":"literal",
                                                "value":0},
{
                                                "computedType":"int",
                                                "sto":"binOp",
                                                "op":"-",
                                                "leftSTO":{
                                                  "computedType":"int",
                                                  "sto":"propCall",
                                                  "thisSTO":{
                                                    "computedType":"string",
                                                    "desiredType":"string",
                                                    "sto":"propCall",
                                                    "thisSTO":{
                                                      "desiredType":"widget",
                                                      "sto":"var",
                                                      "name":"target"},
                                                    "prop":"text"},
                                                  "prop":"length"},
                                                "rightSTO":{
                                                  "computedType":"int",
                                                  "sto":"literal",
                                                  "value":1}}]}]},
{
                                        "exprType":"booleanLiteral",
                                        "value":true}]}]}}]}]}},
                  "tabbable":true},
{
                  "id":"51f289cbb8784749a37fb507b724189b",
                  "label":"",
                  "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":168,
                      "y":339},
                    "size":{
                      "width":80,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 yue 向上滑动 500 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["35c1698940964878827b9498b4c46e89"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"slideUp",
                                      "duration":500,
                                      "showType":"none"}}}]},
{
                              "action":"wait",
                              "description":"等待700毫秒",
                              "waitTime":700},
{
                              "action":"fadeWidget",
                              "description":"隐藏 yue",
                              "objectsToFades":[{
                                  "objectPath":["35c1698940964878827b9498b4c46e89"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"22c579363ffd425087596855bae28471",
                  "label":"phone_number",
                  "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"20px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":22,
                      "y":40},
                    "size":{
                      "width":206,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"207f09878c3b45f5b409d94d844951ca",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"20px",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":22,
                          "y":40},
                        "size":{
                          "width":206,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"35c1698940964878827b9498b4c46e89",
                  "label":"yue",
                  "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":false,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":15,
                      "y":85},
                    "size":{
                      "width":225,
                      "height":48},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"68f6455cc55e417d94620bea77d1ac6b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6c1275ea216431f81ca2b816f2cabe4",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":15,
                          "y":85},
                        "size":{
                          "width":225,
                          "height":48},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"8e1279447001471ea7692b9b2c1d8b24",
          "label":"底部1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":40,
              "y":490},
            "size":{
              "width":250,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef1337e8d0a343dfb2ca92c1446f9951",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":40,
                  "y":490},
                "size":{
                  "width":250,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/底部1_u88.png"}},
{
          "id":"af89d50cb9884275b700c4b9575140ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":58,
              "y":511},
            "size":{
              "width":31,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35e2a6d998ba49a49df65dda01cd7a34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":511},
                "size":{
                  "width":31,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18e155443fa942da91135dea6b3caf85",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":110,
              "y":511},
            "size":{
              "width":37,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"329376a244fc44468f7a0f6942fcf4eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":110,
                  "y":511},
                "size":{
                  "width":37,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"54581bea5e744e5197365e5da5060839",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":170,
              "y":511},
            "size":{
              "width":31,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d624f2ad8624a47a91366618b71f57d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":170,
                  "y":511},
                "size":{
                  "width":31,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5947c735da4844e8ac6a420ff49d1b81",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":233,
              "y":511},
            "size":{
              "width":21,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d38601b0d68541e8bedd0981a3896990",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":233,
                  "y":511},
                "size":{
                  "width":21,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"384ae98c63f1488c80325f4d7ca51f65",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":495},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31c6835994e64c9590c9344b30219286",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":495},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u98.png"}},
{
          "id":"335aebcf11994428ac5905c49c85af77",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":495},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f12a6e2e442e4b4c9817e0307aafe8db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":495},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u100.png"}},
{
          "id":"ae69541371f145ab909f4a11722215b8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":495},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34f4c456191948609eae604f78176169",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":495},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u102.png"}},
{
          "id":"8b7531e2ab5c4bf8bfec90e964ca63e5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":178,
              "y":495},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6535c5b71fee4e8ebc9df3b3c36fe3b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":178,
                  "y":495},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u104.png"}},
{
          "id":"c0934c2c7752447f809256c42e359436",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":495},
            "size":{
              "width":31,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 易电话",
                      "target":{
                        "targetType":"page",
                        "url":"易电话.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"be76ce39ddc547ee9b6878121df56ba4",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":495},
            "size":{
              "width":31,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8d6591f087b548388e77daf6f7ee29f2",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":495},
            "size":{
              "width":31,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个人中心",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"c3b09bc9ed0e47ddaa7d829f2e27c123",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":495},
            "size":{
              "width":37,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 CM商城",
                      "target":{
                        "targetType":"page",
                        "url":"cm商城.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "93fd5d385bb2419698ca8d204db6bd4a":{
      "packageId":"93fd5d385bb2419698ca8d204db6bd4a",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2e194cf0c2b54c5680885a8df07da4e2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":336,
                "height":627}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0c76e3d052f04fcfb070a80a46e1e3f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":336,
                    "height":627}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u1.png"}},
{
            "id":"12b733eb02494e5a8662e96bcc215f5f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":100},
              "size":{
                "width":250,
                "height":430}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18c2b83789bc48f89e71a44ca19cb8ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":100},
                  "size":{
                    "width":250,
                    "height":430}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u3.png"}}]}}},
  "objectPaths":{
    "548b40a3e1ee4b8f96ba6c7422d34545":{
      "scriptId":"u0",
      "2e194cf0c2b54c5680885a8df07da4e2":{
        "scriptId":"u1"},
      "0c76e3d052f04fcfb070a80a46e1e3f9":{
        "scriptId":"u2"},
      "12b733eb02494e5a8662e96bcc215f5f":{
        "scriptId":"u3"},
      "18c2b83789bc48f89e71a44ca19cb8ae":{
        "scriptId":"u4"}},
    "f6c1275ea216431f81ca2b816f2cabe4":{
      "scriptId":"u5"},
    "4f1df17cd4b24109b8b053281c447ffc":{
      "scriptId":"u6"},
    "f1fef5810a584fcaa54445db7e8fc17a":{
      "scriptId":"u7"},
    "dc6192f6fdf94a038b09c3031dc67531":{
      "scriptId":"u8"},
    "42f03becee3b41bba5a1b73e21cd29c1":{
      "scriptId":"u9"},
    "0934f41f81634584b8e790c7ca71db57":{
      "scriptId":"u10"},
    "d6e3527389554618b76e0a762aa3d52d":{
      "scriptId":"u11"},
    "898abf23226f495ea1bc6efa175bdce2":{
      "scriptId":"u12"},
    "6a0103803f5547cdb2ee3c9801b4cca0":{
      "scriptId":"u13"},
    "ce1a107e20a94b07bf35911cdab209a4":{
      "scriptId":"u14"},
    "13566f9af1c2489cad6f637ca6a92189":{
      "scriptId":"u15"},
    "12e7f391fa654ad0a81ef94631c8ba4a":{
      "scriptId":"u16"},
    "f3a255c836b54238bfb310f347d501c1":{
      "scriptId":"u17"},
    "f5597e0f027f41dc82026bdc075a9a45":{
      "scriptId":"u18"},
    "424bdb07ee2d48ccbc7758c4add17b08":{
      "scriptId":"u19"},
    "516ecf1bf70e498c94fe76e80b0dc659":{
      "scriptId":"u20"},
    "ee89e1ef955f463ab8a7de3dc1114759":{
      "scriptId":"u21"},
    "0ab172b119364405946d249e88e633ce":{
      "scriptId":"u22"},
    "51f9864c76ea4729a91e8e4582f9aceb":{
      "scriptId":"u23"},
    "e7972a464fbf4b24991826ff3f7ae4be":{
      "scriptId":"u24"},
    "e946d68ebfe249c6abc7279d057b2904":{
      "scriptId":"u25"},
    "2adfdc5df7e1479ea662be9618759ef5":{
      "scriptId":"u26"},
    "af67db9547364d7184664c6292d196dd":{
      "scriptId":"u27"},
    "9c83bf7e296f421c9761866d4cc9cbb6":{
      "scriptId":"u28"},
    "bc79252bcaff4dd18ceccd994b851fb3":{
      "scriptId":"u29"},
    "178c0650ddb9472e843a9476e8d53902":{
      "scriptId":"u30"},
    "8e24c8124800409b92a3c48b54df423c":{
      "scriptId":"u31"},
    "c8425a2d86f146b1a3f063c3f4ea7f83":{
      "scriptId":"u32"},
    "7813f8c8da2d4502b808a67a0de209bd":{
      "scriptId":"u33"},
    "3ebc00a4c56a44248fded9e5a0a74593":{
      "scriptId":"u34"},
    "db48e7189bfb4c728b535dbe5d045e6b":{
      "scriptId":"u35"},
    "2161da881be44169bd82aad4e85b2cc7":{
      "scriptId":"u36"},
    "1826f5254dba4d2388ff781eece4a60b":{
      "scriptId":"u37"},
    "0ea5bb02ce724c39b5de0aa5a49e65ec":{
      "scriptId":"u38"},
    "6a7cfa9cfc384c94847e2d21d839ba09":{
      "scriptId":"u39"},
    "ce67f494241a457cb71fc7aa0f5fd463":{
      "scriptId":"u40"},
    "b19857ef79f7499e810615b566cc535b":{
      "scriptId":"u41"},
    "19a2d09d338f40fb8fc23fc5448e9cc0":{
      "scriptId":"u42"},
    "d3a492105524431ba56190bedc853849":{
      "scriptId":"u43"},
    "62caf63435894f0db44ee5fdf5d1c4c4":{
      "scriptId":"u44"},
    "53bbd6cd715c472b98d217b65f58e4d8":{
      "scriptId":"u45"},
    "51f289cbb8784749a37fb507b724189b":{
      "scriptId":"u46"},
    "22c579363ffd425087596855bae28471":{
      "scriptId":"u47"},
    "207f09878c3b45f5b409d94d844951ca":{
      "scriptId":"u48"},
    "35c1698940964878827b9498b4c46e89":{
      "scriptId":"u49"},
    "68f6455cc55e417d94620bea77d1ac6b":{
      "scriptId":"u50"},
    "8e1279447001471ea7692b9b2c1d8b24":{
      "scriptId":"u51"},
    "ef1337e8d0a343dfb2ca92c1446f9951":{
      "scriptId":"u52"},
    "af89d50cb9884275b700c4b9575140ef":{
      "scriptId":"u53"},
    "35e2a6d998ba49a49df65dda01cd7a34":{
      "scriptId":"u54"},
    "18e155443fa942da91135dea6b3caf85":{
      "scriptId":"u55"},
    "329376a244fc44468f7a0f6942fcf4eb":{
      "scriptId":"u56"},
    "54581bea5e744e5197365e5da5060839":{
      "scriptId":"u57"},
    "1d624f2ad8624a47a91366618b71f57d":{
      "scriptId":"u58"},
    "5947c735da4844e8ac6a420ff49d1b81":{
      "scriptId":"u59"},
    "d38601b0d68541e8bedd0981a3896990":{
      "scriptId":"u60"},
    "384ae98c63f1488c80325f4d7ca51f65":{
      "scriptId":"u61"},
    "31c6835994e64c9590c9344b30219286":{
      "scriptId":"u62"},
    "335aebcf11994428ac5905c49c85af77":{
      "scriptId":"u63"},
    "f12a6e2e442e4b4c9817e0307aafe8db":{
      "scriptId":"u64"},
    "ae69541371f145ab909f4a11722215b8":{
      "scriptId":"u65"},
    "34f4c456191948609eae604f78176169":{
      "scriptId":"u66"},
    "8b7531e2ab5c4bf8bfec90e964ca63e5":{
      "scriptId":"u67"},
    "6535c5b71fee4e8ebc9df3b3c36fe3b8":{
      "scriptId":"u68"},
    "c0934c2c7752447f809256c42e359436":{
      "scriptId":"u69"},
    "be76ce39ddc547ee9b6878121df56ba4":{
      "scriptId":"u70"},
    "8d6591f087b548388e77daf6f7ee29f2":{
      "scriptId":"u71"},
    "c3b09bc9ed0e47ddaa7d829f2e27c123":{
      "scriptId":"u72"}}});