$axure.loadCurrentPage({
  "url":"收货地址_1.html",
  "generationDate":new Date(1448007540661.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"bohao"],
  "page":{
    "packageId":"9f39b805b4c04e078698f5f1373eb350",
    "type":"Axure:Page",
    "name":"收货地址",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5d9a2560042842699a41aa7531629f26",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"93fd5d385bb2419698ca8d204db6bd4a"},
{
          "id":"f19f58b9407749aa8da6baf30d019c7b",
          "label":"dizhi",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":250,
              "height":430}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e7dab6f4a8f44ff991efadb005f57528",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"22640b94b08a44018c9f66b81b3caa98",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5e21fb0d36fe458ebaa2a115156af7fb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"13a6d50442654f64bd3108e0f7e37b81",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":98,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f3a93fd793cc420eb6a4cf188d841436",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":98,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1754f3da3223401bba129eac7991168a",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":7},
                    "size":{
                      "width":35,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"72519e34bdba43fd8b833b20f3f0239e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":7},
                        "size":{
                          "width":35,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 兑换页面",
                              "target":{
                                "targetType":"page",
                                "url":"兑换页面_1.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"565cde90250c4f63be047a5b53858c38",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":106},
                    "size":{
                      "width":250,
                      "height":84},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a37afb640024c23b548d4b7935841b9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":106},
                        "size":{
                          "width":250,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u452.png"}},
{
                  "id":"9cb47de87d854c92b9f60310acc4a96b",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":250,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2a1c8d2194a04e2f97a8d4600d96fb17",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":250,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u454.png"}},
{
                  "id":"7a4d0047dafa444f835ab45e6b6e7063",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":58,
                      "y":34},
                    "size":{
                      "width":32,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3076a1aac8a04740a2ceb66fc1b0e4ca",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":58,
                          "y":34},
                        "size":{
                          "width":32,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u456.png"}},
{
                  "id":"66fd68285c1746caa1d917009855aaa1",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":100,
                      "y":40.5},
                    "size":{
                      "width":65,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"19839a9d8d694da1b97882f0f4c472be",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":100,
                          "y":40.5},
                        "size":{
                          "width":65,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c464cc9111ef45c98a2673edaf44c978",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "location":{
                      "x":8,
                      "y":80},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"33f57e3080a2453f92cf1b5e292e8c4d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "location":{
                          "x":8,
                          "y":80},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8ab6ec30602247c080d784e9aa2b70f9",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":114},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e4f95bc59535463eb81d593a6b91f18a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":114},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"053ae2c78d094015a4e009dc0a58f1cc",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":140},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8dd065983d7344fcb74319362377b202",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":140},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1672976313024540864d37cf02a36847",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":166},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9b9fd8bdb45f4f68a53bb50e889ef32e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":166},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9d86be8c36fe4769accb1a652a664354",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":250,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 dizhi to tianjia",
                              "panelsToStates":[{
                                  "panelPath":["f19f58b9407749aa8da6baf30d019c7b"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"8d97a91508fa44428b26b73c6eeab16f",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"ae0ed15ae72a4675995381189ba478fc",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":200},
                    "size":{
                      "width":250,
                      "height":84},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f8c4237e01ef48709177e50640e2ca82",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":200},
                        "size":{
                          "width":250,
                          "height":84},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u452.png"}},
{
                  "id":"92d5d7e9dbf543a8804ae1204b6bef22",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":208},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45651bc363864ce6ae65d7ced00886e7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":208},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7824655afe8a401586bfc41c7b8046f3",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":234},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df544759b6f045fab830e213fbd69cd6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":234},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e98c57149232446b8807de6e04f70757",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":260},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"337fbb8ee88145a5acd18c8a0d8ae477",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":13,
                          "y":260},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"e85f69f6f422471b8a5a6f9b38e2165b",
              "label":"tianjia",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"782b0bcdf3464d2ba436767a34677789",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e45002b28d7c4e6daf31c94e0a925b62",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"eb35bab8165b4c8a86ceea12799c6cc9",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":98,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"34daf9264c85435a986c8699e1304e55",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":98,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"05d9a521bda7471da1d6038e31946942",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":7},
                    "size":{
                      "width":35,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"88e7e9e4088647edbd1ec23ade3d5e2e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":7},
                        "size":{
                          "width":35,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 dizhi to State1",
                              "panelsToStates":[{
                                  "panelPath":["f19f58b9407749aa8da6baf30d019c7b"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b480a1fe98b04c1ca3d65b4d21d2f99d",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":250,
                      "height":140}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"657550e6f88149dd9ba8c5875384a234",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":40},
                        "size":{
                          "width":250,
                          "height":140}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u483.png"}},
{
                  "id":"a8d9079874c24f4386cf80ed7402fb5f",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":50},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9af2e383dc344d5a885823663a80595",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":50},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"584298ece35e419790fa7ae7b306addb",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":69},
                    "size":{
                      "width":210,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/个人中心/u487_line.png"}},
{
                  "id":"b6e768c3db4646019766ccba478dfaf3",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "hint":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1}}},
                    "location":{
                      "x":70,
                      "y":45.5},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "placeholderText":"请填写收货人姓名"},
{
                  "id":"8219fe2a98b34e29934e75f2de8c0748",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":85},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d57b0accd14416aa9b3dc6efa4704c5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":85},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d911c8a57e1947a59584a9d9d46ba8c6",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "hint":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1}}},
                    "location":{
                      "x":70,
                      "y":81},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "placeholderText":"请填写联系电话"},
{
                  "id":"43f3fc5f33da491394cb2383bb73c5a6",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":101},
                    "size":{
                      "width":210,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/个人中心/u487_line.png"}},
{
                  "id":"4c6b891cb9054647b03cac237b39b3d5",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":120},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"240ad2e029734fe3b384da7fa0cd2a31",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":120},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"64b6819be40040679e80e861b13d1794",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "hint":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1}}},
                    "location":{
                      "x":73,
                      "y":148},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "placeholderText":"请填写详细地址"},
{
                  "id":"a3cace03a39c46f6806b219fd54490c8",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":13,
                      "y":136},
                    "size":{
                      "width":210,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/个人中心/u487_line.png"}},
{
                  "id":"ce6652727d604fe4ba85408ca88cfbbd",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":70,
                      "y":116},
                    "size":{
                      "width":50,
                      "height":22}},
                  "adaptiveStyles":{
}},
{
                  "id":"b653b9deae7242b6901c86e2fd12fd07",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":130,
                      "y":116},
                    "size":{
                      "width":50,
                      "height":22}},
                  "adaptiveStyles":{
}},
{
                  "id":"c1838346c9664695ae9311dbb486b3c9",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":190,
                      "y":116},
                    "size":{
                      "width":50,
                      "height":22}},
                  "adaptiveStyles":{
}},
{
                  "id":"565a04b1a4b74f58a4b4c5e0d53a8cc7",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":152},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2fb00d723883421292ae3b5559fae0de",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":152},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d9bef662bdbb4d1d8abe46116d4325ef",
                  "label":"",
                  "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":190},
                    "size":{
                      "width":190,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e0cf9e33afda4dea8fa2baf11bf4a3ed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f19f58b9407749aa8da6baf30d019c7b",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":190},
                        "size":{
                          "width":190,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 dizhi to State1",
                              "panelsToStates":[{
                                  "panelPath":["f19f58b9407749aa8da6baf30d019c7b"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/index/u43.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "93fd5d385bb2419698ca8d204db6bd4a":{
      "packageId":"93fd5d385bb2419698ca8d204db6bd4a",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2e194cf0c2b54c5680885a8df07da4e2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":336,
                "height":627}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0c76e3d052f04fcfb070a80a46e1e3f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":336,
                    "height":627}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u1.png"}},
{
            "id":"12b733eb02494e5a8662e96bcc215f5f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":100},
              "size":{
                "width":250,
                "height":430}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18c2b83789bc48f89e71a44ca19cb8ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":100},
                  "size":{
                    "width":250,
                    "height":430}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u3.png"}}]}}},
  "objectPaths":{
    "5d9a2560042842699a41aa7531629f26":{
      "scriptId":"u0",
      "2e194cf0c2b54c5680885a8df07da4e2":{
        "scriptId":"u1"},
      "0c76e3d052f04fcfb070a80a46e1e3f9":{
        "scriptId":"u2"},
      "12b733eb02494e5a8662e96bcc215f5f":{
        "scriptId":"u3"},
      "18c2b83789bc48f89e71a44ca19cb8ae":{
        "scriptId":"u4"}},
    "f19f58b9407749aa8da6baf30d019c7b":{
      "scriptId":"u5"},
    "22640b94b08a44018c9f66b81b3caa98":{
      "scriptId":"u6"},
    "5e21fb0d36fe458ebaa2a115156af7fb":{
      "scriptId":"u7"},
    "13a6d50442654f64bd3108e0f7e37b81":{
      "scriptId":"u8"},
    "f3a93fd793cc420eb6a4cf188d841436":{
      "scriptId":"u9"},
    "1754f3da3223401bba129eac7991168a":{
      "scriptId":"u10"},
    "72519e34bdba43fd8b833b20f3f0239e":{
      "scriptId":"u11"},
    "565cde90250c4f63be047a5b53858c38":{
      "scriptId":"u12"},
    "7a37afb640024c23b548d4b7935841b9":{
      "scriptId":"u13"},
    "9cb47de87d854c92b9f60310acc4a96b":{
      "scriptId":"u14"},
    "2a1c8d2194a04e2f97a8d4600d96fb17":{
      "scriptId":"u15"},
    "7a4d0047dafa444f835ab45e6b6e7063":{
      "scriptId":"u16"},
    "3076a1aac8a04740a2ceb66fc1b0e4ca":{
      "scriptId":"u17"},
    "66fd68285c1746caa1d917009855aaa1":{
      "scriptId":"u18"},
    "19839a9d8d694da1b97882f0f4c472be":{
      "scriptId":"u19"},
    "c464cc9111ef45c98a2673edaf44c978":{
      "scriptId":"u20"},
    "33f57e3080a2453f92cf1b5e292e8c4d":{
      "scriptId":"u21"},
    "8ab6ec30602247c080d784e9aa2b70f9":{
      "scriptId":"u22"},
    "e4f95bc59535463eb81d593a6b91f18a":{
      "scriptId":"u23"},
    "053ae2c78d094015a4e009dc0a58f1cc":{
      "scriptId":"u24"},
    "8dd065983d7344fcb74319362377b202":{
      "scriptId":"u25"},
    "1672976313024540864d37cf02a36847":{
      "scriptId":"u26"},
    "9b9fd8bdb45f4f68a53bb50e889ef32e":{
      "scriptId":"u27"},
    "9d86be8c36fe4769accb1a652a664354":{
      "scriptId":"u28"},
    "ae0ed15ae72a4675995381189ba478fc":{
      "scriptId":"u29"},
    "f8c4237e01ef48709177e50640e2ca82":{
      "scriptId":"u30"},
    "92d5d7e9dbf543a8804ae1204b6bef22":{
      "scriptId":"u31"},
    "45651bc363864ce6ae65d7ced00886e7":{
      "scriptId":"u32"},
    "7824655afe8a401586bfc41c7b8046f3":{
      "scriptId":"u33"},
    "df544759b6f045fab830e213fbd69cd6":{
      "scriptId":"u34"},
    "e98c57149232446b8807de6e04f70757":{
      "scriptId":"u35"},
    "337fbb8ee88145a5acd18c8a0d8ae477":{
      "scriptId":"u36"},
    "782b0bcdf3464d2ba436767a34677789":{
      "scriptId":"u37"},
    "e45002b28d7c4e6daf31c94e0a925b62":{
      "scriptId":"u38"},
    "eb35bab8165b4c8a86ceea12799c6cc9":{
      "scriptId":"u39"},
    "34daf9264c85435a986c8699e1304e55":{
      "scriptId":"u40"},
    "05d9a521bda7471da1d6038e31946942":{
      "scriptId":"u41"},
    "88e7e9e4088647edbd1ec23ade3d5e2e":{
      "scriptId":"u42"},
    "b480a1fe98b04c1ca3d65b4d21d2f99d":{
      "scriptId":"u43"},
    "657550e6f88149dd9ba8c5875384a234":{
      "scriptId":"u44"},
    "a8d9079874c24f4386cf80ed7402fb5f":{
      "scriptId":"u45"},
    "e9af2e383dc344d5a885823663a80595":{
      "scriptId":"u46"},
    "584298ece35e419790fa7ae7b306addb":{
      "scriptId":"u47"},
    "b6e768c3db4646019766ccba478dfaf3":{
      "scriptId":"u48"},
    "8219fe2a98b34e29934e75f2de8c0748":{
      "scriptId":"u49"},
    "7d57b0accd14416aa9b3dc6efa4704c5":{
      "scriptId":"u50"},
    "d911c8a57e1947a59584a9d9d46ba8c6":{
      "scriptId":"u51"},
    "43f3fc5f33da491394cb2383bb73c5a6":{
      "scriptId":"u52"},
    "4c6b891cb9054647b03cac237b39b3d5":{
      "scriptId":"u53"},
    "240ad2e029734fe3b384da7fa0cd2a31":{
      "scriptId":"u54"},
    "64b6819be40040679e80e861b13d1794":{
      "scriptId":"u55"},
    "a3cace03a39c46f6806b219fd54490c8":{
      "scriptId":"u56"},
    "ce6652727d604fe4ba85408ca88cfbbd":{
      "scriptId":"u57"},
    "b653b9deae7242b6901c86e2fd12fd07":{
      "scriptId":"u58"},
    "c1838346c9664695ae9311dbb486b3c9":{
      "scriptId":"u59"},
    "565a04b1a4b74f58a4b4c5e0d53a8cc7":{
      "scriptId":"u60"},
    "2fb00d723883421292ae3b5559fae0de":{
      "scriptId":"u61"},
    "d9bef662bdbb4d1d8abe46116d4325ef":{
      "scriptId":"u62"},
    "e0cf9e33afda4dea8fa2baf11bf4a3ed":{
      "scriptId":"u63"}}});