$axure.loadCurrentPage({
  "url":"商品分类.html",
  "generationDate":new Date(1448007540012.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"bohao"],
  "page":{
    "packageId":"82c0fc3fdf074ea1a8419a2b15bbe4b6",
    "type":"Axure:Page",
    "name":"商品分类",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5f20cc1d3a5c46f9bc5b5f625b2e099b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"93fd5d385bb2419698ca8d204db6bd4a"},
{
          "id":"dd25e3b85d0c4c87aae2698a7cb44f46",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":250,
              "height":430}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"7700bc10fd44446db56961ded6f9f958",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"14142ed48bda4cc1b371fc1f3e0ee0a6",
                  "label":"",
                  "parentDynamicPanel":"dd25e3b85d0c4c87aae2698a7cb44f46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c4e97590cca14eb38e0e16e865ce488d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd25e3b85d0c4c87aae2698a7cb44f46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"4c4f79dbf5684481bd5fdf32b11fe1c9",
                  "label":"",
                  "parentDynamicPanel":"dd25e3b85d0c4c87aae2698a7cb44f46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":98,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1501e686022e46d98c5dca92f11a578d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd25e3b85d0c4c87aae2698a7cb44f46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":98,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0c8ea6869c304052a34b81093a93deab",
                  "label":"",
                  "parentDynamicPanel":"dd25e3b85d0c4c87aae2698a7cb44f46",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":7},
                    "size":{
                      "width":35,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6498e5fa64d0495ba8ef60924be5c46b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd25e3b85d0c4c87aae2698a7cb44f46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":7},
                        "size":{
                          "width":35,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 CM商城",
                              "target":{
                                "targetType":"page",
                                "url":"cm商城.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"57eef3999bc645c08a09d1b8b6026ca2",
                  "label":"",
                  "parentDynamicPanel":"dd25e3b85d0c4c87aae2698a7cb44f46",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":250,
                      "height":360}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"41d35ad655934bc9b1a416177cf49a48",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dd25e3b85d0c4c87aae2698a7cb44f46",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":250,
                          "height":360}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 分类页面",
                              "target":{
                                "targetType":"page",
                                "url":"分类页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/商品分类/u12.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "93fd5d385bb2419698ca8d204db6bd4a":{
      "packageId":"93fd5d385bb2419698ca8d204db6bd4a",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2e194cf0c2b54c5680885a8df07da4e2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":336,
                "height":627}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0c76e3d052f04fcfb070a80a46e1e3f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":336,
                    "height":627}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u1.png"}},
{
            "id":"12b733eb02494e5a8662e96bcc215f5f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":100},
              "size":{
                "width":250,
                "height":430}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18c2b83789bc48f89e71a44ca19cb8ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":100},
                  "size":{
                    "width":250,
                    "height":430}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u3.png"}}]}}},
  "objectPaths":{
    "5f20cc1d3a5c46f9bc5b5f625b2e099b":{
      "scriptId":"u0",
      "2e194cf0c2b54c5680885a8df07da4e2":{
        "scriptId":"u1"},
      "0c76e3d052f04fcfb070a80a46e1e3f9":{
        "scriptId":"u2"},
      "12b733eb02494e5a8662e96bcc215f5f":{
        "scriptId":"u3"},
      "18c2b83789bc48f89e71a44ca19cb8ae":{
        "scriptId":"u4"}},
    "dd25e3b85d0c4c87aae2698a7cb44f46":{
      "scriptId":"u5"},
    "14142ed48bda4cc1b371fc1f3e0ee0a6":{
      "scriptId":"u6"},
    "c4e97590cca14eb38e0e16e865ce488d":{
      "scriptId":"u7"},
    "4c4f79dbf5684481bd5fdf32b11fe1c9":{
      "scriptId":"u8"},
    "1501e686022e46d98c5dca92f11a578d":{
      "scriptId":"u9"},
    "0c8ea6869c304052a34b81093a93deab":{
      "scriptId":"u10"},
    "6498e5fa64d0495ba8ef60924be5c46b":{
      "scriptId":"u11"},
    "57eef3999bc645c08a09d1b8b6026ca2":{
      "scriptId":"u12"},
    "41d35ad655934bc9b1a416177cf49a48":{
      "scriptId":"u13"}}});