$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1448007538932.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"bohao"],
  "page":{
    "packageId":"e65b9bc70c314e6ebe25afeba086a21c",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aec4e622f67b4b57acdc4b2e7515ff7e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"93fd5d385bb2419698ca8d204db6bd4a"},
{
          "id":"790e8c0b526841b9aaebdb307546fd1e",
          "label":"shouye",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":250,
              "height":580}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"拖动限制<br> (If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 shouye 纵向拖动",
                      "objectsToMoves":[{
                          "objectPath":["790e8c0b526841b9aaebdb307546fd1e"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]},
{
                  "description":"向下拖动<br> (If area of shouye 未接触 area of 顶部)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["790e8c0b526841b9aaebdb307546fd1e"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["4c489be7da3e479089bc326a5ef9083c"]}]}]},
                  "actions":[{
                      "action":"wait",
                      "description":"等待50毫秒",
                      "waitTime":50},
{
                      "action":"moveWidget",
                      "description":"移动 shouye 到 (40,100)",
                      "objectsToMoves":[{
                          "objectPath":["790e8c0b526841b9aaebdb307546fd1e"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"40",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"100",
                              "stos":[]},
                            "options":{
}}}]}]},
{
                  "description":"向上拖动<br> (If area of shouye 未接触 area of 底部1)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["790e8c0b526841b9aaebdb307546fd1e"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["2e92f6952ab24725a9aad1d57c76c249"]}]}]},
                  "actions":[{
                      "action":"wait",
                      "description":"等待50毫秒",
                      "waitTime":50},
{
                      "action":"moveWidget",
                      "description":"移动 shouye 到 (40,-90)",
                      "objectsToMoves":[{
                          "objectPath":["790e8c0b526841b9aaebdb307546fd1e"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"40",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"-90",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c4a367b5914247dda78d9d06aff1ab8d",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fc4fb9148d394dbfb563fbcb3418d67a",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0ad9ecef378b4c71bc25106ce3f70e59",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"9a45fef11e864142ae8c27be7e8141c4",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":109,
                      "y":7},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"099d105351fd44cfa82973457d4e66df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":109,
                          "y":7},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ed2d096a0ff64eb2b887d1a12c908c0b",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":81},
                    "size":{
                      "width":63,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d06a63ef7d614f1eb1400c19f8cd5f47",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":81},
                        "size":{
                          "width":63,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u10.png"}},
{
                  "id":"90cd6fe44aca4fa183e0dd727fc8521f",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":63,
                      "y":81},
                    "size":{
                      "width":62,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a456502c02c24c3a887b748e6c1bbfbf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":63,
                          "y":81},
                        "size":{
                          "width":62,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u12.png"}},
{
                  "id":"929d398026ca46e18408208caa945d45",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":125,
                      "y":81},
                    "size":{
                      "width":62,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"46e1434b43644148aac8227915bef678",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":125,
                          "y":81},
                        "size":{
                          "width":62,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u12.png"}},
{
                  "id":"8b44fcef0c4f43ec8632464e829d7de3",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":187,
                      "y":81},
                    "size":{
                      "width":63,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dbc4bdb354ef4afd86658c70b440bd64",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":187,
                          "y":81},
                        "size":{
                          "width":63,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u10.png"}},
{
                  "id":"5eac3703a9fb4ae1b512a388817741c5",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":151},
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d4f0d195443f4c5eb196b96fb72c1438",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":151},
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"bf9284b1c17240f0b2c05cd18e4461ad",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":103},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"93666a9a52a44c799a2eb121819f3178",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":103},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"36bedd7b34a0468fa1925e202dcf9a0b",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":74,
                      "y":103},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c7c5359359c2436297db754f171d8b43",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":74,
                          "y":103},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"74d28de431d948e5abeca6084c49cff1",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":137,
                      "y":103},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"25b34c02a37641368248f387bb28387f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":137,
                          "y":103},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d95a6fc2c7474e3099f5d6e4166b3dbf",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":198,
                      "y":103},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cdd08a94387d49848758d742d09d07ab",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":198,
                          "y":103},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9bd062df7a7e4de299744a95f1cbf555",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":158},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fb7176ebba304749be59135c9c3e17e2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":158},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"938d68ca3d704969b60834235a6ac2af",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":201},
                    "size":{
                      "width":98,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"455c8a29f2cc43b9b9268b8021c83717",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":201},
                        "size":{
                          "width":98,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u30.png"}},
{
                  "id":"3202c0eea1ab49f49a9d47c29ee67234",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":137,
                      "y":201},
                    "size":{
                      "width":98,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45f4576797ba4dfb969eaaeffd90a460",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":137,
                          "y":201},
                        "size":{
                          "width":98,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u30.png"}},
{
                  "id":"5c485d98f51a4a47ab6690466785244d",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":31,
                      "y":283},
                    "size":{
                      "width":60,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f84cad4cd65f44e7bac82bdb0a671b32",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":31,
                          "y":283},
                        "size":{
                          "width":60,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6f666a87df22415588f30bc99f64fa72",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":156,
                      "y":283},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"abdb93d7066a46ce835b90ecb3db3002",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":156,
                          "y":283},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"021c995d24564651b7dfc38a384703b0",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":24,
                      "y":299},
                    "size":{
                      "width":73,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3176fde008f24617b05dd97ca820c651",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":24,
                          "y":299},
                        "size":{
                          "width":73,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8188ca8fc9354eceaa075664b0c7b396",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":150,
                      "y":299},
                    "size":{
                      "width":73,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0784af9a205a43e5a6ac012b2eaaba66",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":150,
                          "y":299},
                        "size":{
                          "width":73,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"39b01e0419fb4f50bf7a6c36ba94535e",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":14,
                      "y":325},
                    "size":{
                      "width":98,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"54c7fec940c64668bd9128bc12635ae9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":14,
                          "y":325},
                        "size":{
                          "width":98,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u30.png"}},
{
                  "id":"dcacaa1039d24e738578304b6e17dd3a",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":138,
                      "y":325},
                    "size":{
                      "width":98,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"39ca62b3a33b443da1732c02c67d61f6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":138,
                          "y":325},
                        "size":{
                          "width":98,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u30.png"}},
{
                  "id":"97b857c78f59450b91c1d6b1ce9234be",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":32,
                      "y":407},
                    "size":{
                      "width":60,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c356cc3596c941e59aa9dc10994b7670",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":32,
                          "y":407},
                        "size":{
                          "width":60,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"72fa739bb5b2439d8e9d390afb444e3d",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":158,
                      "y":407},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a852923ec064dbf9ff2969d1a2ade2a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":158,
                          "y":407},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6f8115e6d27b4931b22cb4f9c39ec6c4",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":26,
                      "y":423},
                    "size":{
                      "width":73,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8a202d998ecc4b6f9410154a80ac340b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":26,
                          "y":423},
                        "size":{
                          "width":73,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"71c7d18f915943978586482bfddf4855",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":152,
                      "y":423},
                    "size":{
                      "width":73,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7bb16fcfa5154010b040efb76a2bfb72",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":152,
                          "y":423},
                        "size":{
                          "width":73,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c9c4d6d2a824462e81b93835ff7cf88c",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":449},
                    "size":{
                      "width":98,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c7c96e86a0594d028816884a170fb6e6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":449},
                        "size":{
                          "width":98,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u30.png"}},
{
                  "id":"bf4d1ccc42c14225bea9353fc2e7cc38",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":136,
                      "y":449},
                    "size":{
                      "width":98,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85779be9f2c04aeba48ae7e77e6efe07",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":136,
                          "y":449},
                        "size":{
                          "width":98,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u30.png"}},
{
                  "id":"ac34d7c4872d4546969ae72a3d02ba9f",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":531},
                    "size":{
                      "width":60,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c0bc06fadf7c41f88f07961c56f0cc52",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":531},
                        "size":{
                          "width":60,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7d94f5192fae4a41b416761e9445f9e1",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":156,
                      "y":531},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9e8f1c1232844537a72c9bfe23435439",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":156,
                          "y":531},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d7d7e481f35d407fa925c939f01bd675",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":24,
                      "y":547},
                    "size":{
                      "width":73,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ea5775eb20d6459a96463923f82b1062",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":24,
                          "y":547},
                        "size":{
                          "width":73,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"14f0e2340ab747b48dbf84e5b2250753",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":150,
                      "y":547},
                    "size":{
                      "width":73,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a7fa69d6d8864c8aba94b7f84b3f1d66",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":150,
                          "y":547},
                        "size":{
                          "width":73,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"62e5cfe21b0d4be282af8193b09f7786",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":7},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b1ffd247f09466e8065083cccb6ee0a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":220,
                          "y":7},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 消息中心",
                              "target":{
                                "targetType":"page",
                                "url":"消息中心.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u66.png"}},
{
                  "id":"f5685feb00394056845c3abfdf563ddf",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":201},
                    "size":{
                      "width":98,
                      "height":114}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 商品页面",
                              "target":{
                                "targetType":"page",
                                "url":"商品页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"52bcd7d5de7f4a04aa8c720103ab5e2c",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":137,
                      "y":201},
                    "size":{
                      "width":98,
                      "height":114}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 商品页面",
                              "target":{
                                "targetType":"page",
                                "url":"商品页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"3ee60b22057e4d00a251adb8feda68fa",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":14,
                      "y":325},
                    "size":{
                      "width":98,
                      "height":114}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 商品页面",
                              "target":{
                                "targetType":"page",
                                "url":"商品页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"6930b3f417a44ad5937b9bfbba8317c2",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":137,
                      "y":325},
                    "size":{
                      "width":98,
                      "height":114}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 商品页面",
                              "target":{
                                "targetType":"page",
                                "url":"商品页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"e1056eeb12514b38b5aa66b0ad238664",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":449},
                    "size":{
                      "width":98,
                      "height":114}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 商品页面",
                              "target":{
                                "targetType":"page",
                                "url":"商品页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"ccefc98f74ec4ff3b549e8017817bcb0",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":136,
                      "y":449},
                    "size":{
                      "width":98,
                      "height":114}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 商品页面",
                              "target":{
                                "targetType":"page",
                                "url":"商品页面.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"c1632e6b4fc046f78a70b890bb58b783",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":81},
                    "size":{
                      "width":63,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 捡易币",
                              "target":{
                                "targetType":"page",
                                "url":"捡易币.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"bd0965957542481db37d3615ee385e1b",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":63,
                      "y":81},
                    "size":{
                      "width":63,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 抢红包",
                              "target":{
                                "targetType":"page",
                                "url":"抢红包.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"68a624df893449e0a5f5754f6fd187ce",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":124,
                      "y":81},
                    "size":{
                      "width":63,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 看红包",
                              "target":{
                                "targetType":"page",
                                "url":"看红包.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"7831828fe1c542fab5977b72d5ff2052",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":187,
                      "y":81},
                    "size":{
                      "width":63,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 玩红包",
                              "target":{
                                "targetType":"page",
                                "url":"玩红包.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"f45428a17d624aa8ae7deeaf43c7bf9c",
                  "label":"",
                  "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":250,
                      "height":51}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"398d27e653b34411aaba59f976dfdaa8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"790e8c0b526841b9aaebdb307546fd1e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":250,
                          "height":51}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u78.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"4c489be7da3e479089bc326a5ef9083c",
          "label":"顶部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":40,
              "y":80},
            "size":{
              "width":250,
              "height":20},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"986ae793a8ce4ee5878eddb8348d6b6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":40,
                  "y":80},
                "size":{
                  "width":250,
                  "height":20},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/顶部_u80.png"}},
{
          "id":"60c5f4f6523d47bd85f22a947e3a528c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":530},
            "size":{
              "width":356,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eee7d82d3b91474c90cb506b399eead4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":530},
                "size":{
                  "width":356,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u82.png"}},
{
          "id":"19860af0042a4c4390a03b60de809ff8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":2},
            "size":{
              "width":327,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e1bf18e6d754843ba0ceea9f432d4d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":2},
                "size":{
                  "width":327,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u84.png"}},
{
          "id":"e4cc5dfa6cb1479fab012b49d208fde2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":336,
              "height":2},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1719e26768c848a19c88166d5775b275",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":336,
                  "height":2},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u86.png"}},
{
          "id":"2e92f6952ab24725a9aad1d57c76c249",
          "label":"底部1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":490},
            "size":{
              "width":250,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1561270163f4096955a436649f19d06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":490},
                "size":{
                  "width":250,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/底部1_u88.png"}},
{
          "id":"faff7176cb7948f9822c1735923dad5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":58,
              "y":511},
            "size":{
              "width":31,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"962d5e2cdccc43db8c5b7d0261ef1845",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":58,
                  "y":511},
                "size":{
                  "width":31,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bfd52c3a7114804a204d8d7b9950eba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":110,
              "y":511},
            "size":{
              "width":37,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24335a4f82d44a1b8d2df3630e66be6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":110,
                  "y":511},
                "size":{
                  "width":37,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6570762b1010488ba42fc310aa6e2e97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":170,
              "y":511},
            "size":{
              "width":31,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c9670bf8de0420a9f9db85b4cb2c622",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":170,
                  "y":511},
                "size":{
                  "width":31,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c59a4093cea24a0584725ee961297ec6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":233,
              "y":511},
            "size":{
              "width":21,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a2485446d9346988920f87e7f1c4e89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":233,
                  "y":511},
                "size":{
                  "width":21,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d9794ea3d3e4302a5afd870b0ca264c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":66,
              "y":495},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca87db4de3b748c599a1204b7aedeaff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":66,
                  "y":495},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u98.png"}},
{
          "id":"4eec94166af248f5a7176fe2908fa80c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":235,
              "y":495},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5562d8fa19a4723bd6119d64a7e416c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":235,
                  "y":495},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u100.png"}},
{
          "id":"31453eec862145c3a8aea6f81ae33b72",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":118,
              "y":495},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"915f423893fa469bbf3195452d83f361",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":118,
                  "y":495},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u102.png"}},
{
          "id":"e56f4051695c4c988056bf98c062e08c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":178,
              "y":495},
            "size":{
              "width":16,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e5d184031fd44c9fa943c331ed26cb24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":178,
                  "y":495},
                "size":{
                  "width":16,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u104.png"}},
{
          "id":"b2502c65eaa14892962227b940a3e790",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":495},
            "size":{
              "width":31,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 易电话",
                      "target":{
                        "targetType":"page",
                        "url":"易电话.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"af58ad46475d43e5a2aa87fc3bfdf385",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":495},
            "size":{
              "width":31,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"785e0123e7da4b1aadf33b34048ad7f7",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":495},
            "size":{
              "width":31,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个人中心",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"210a9f4db1b0431b8c44ab54d776475b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":495},
            "size":{
              "width":37,
              "height":29}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 CM商城",
                      "target":{
                        "targetType":"page",
                        "url":"cm商城.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "93fd5d385bb2419698ca8d204db6bd4a":{
      "packageId":"93fd5d385bb2419698ca8d204db6bd4a",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2e194cf0c2b54c5680885a8df07da4e2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":336,
                "height":627}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0c76e3d052f04fcfb070a80a46e1e3f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":336,
                    "height":627}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u1.png"}},
{
            "id":"12b733eb02494e5a8662e96bcc215f5f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":100},
              "size":{
                "width":250,
                "height":430}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18c2b83789bc48f89e71a44ca19cb8ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":100},
                  "size":{
                    "width":250,
                    "height":430}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u3.png"}}]}}},
  "objectPaths":{
    "aec4e622f67b4b57acdc4b2e7515ff7e":{
      "scriptId":"u0",
      "2e194cf0c2b54c5680885a8df07da4e2":{
        "scriptId":"u1"},
      "0c76e3d052f04fcfb070a80a46e1e3f9":{
        "scriptId":"u2"},
      "12b733eb02494e5a8662e96bcc215f5f":{
        "scriptId":"u3"},
      "18c2b83789bc48f89e71a44ca19cb8ae":{
        "scriptId":"u4"}},
    "790e8c0b526841b9aaebdb307546fd1e":{
      "scriptId":"u5"},
    "fc4fb9148d394dbfb563fbcb3418d67a":{
      "scriptId":"u6"},
    "0ad9ecef378b4c71bc25106ce3f70e59":{
      "scriptId":"u7"},
    "9a45fef11e864142ae8c27be7e8141c4":{
      "scriptId":"u8"},
    "099d105351fd44cfa82973457d4e66df":{
      "scriptId":"u9"},
    "ed2d096a0ff64eb2b887d1a12c908c0b":{
      "scriptId":"u10"},
    "d06a63ef7d614f1eb1400c19f8cd5f47":{
      "scriptId":"u11"},
    "90cd6fe44aca4fa183e0dd727fc8521f":{
      "scriptId":"u12"},
    "a456502c02c24c3a887b748e6c1bbfbf":{
      "scriptId":"u13"},
    "929d398026ca46e18408208caa945d45":{
      "scriptId":"u14"},
    "46e1434b43644148aac8227915bef678":{
      "scriptId":"u15"},
    "8b44fcef0c4f43ec8632464e829d7de3":{
      "scriptId":"u16"},
    "dbc4bdb354ef4afd86658c70b440bd64":{
      "scriptId":"u17"},
    "5eac3703a9fb4ae1b512a388817741c5":{
      "scriptId":"u18"},
    "d4f0d195443f4c5eb196b96fb72c1438":{
      "scriptId":"u19"},
    "bf9284b1c17240f0b2c05cd18e4461ad":{
      "scriptId":"u20"},
    "93666a9a52a44c799a2eb121819f3178":{
      "scriptId":"u21"},
    "36bedd7b34a0468fa1925e202dcf9a0b":{
      "scriptId":"u22"},
    "c7c5359359c2436297db754f171d8b43":{
      "scriptId":"u23"},
    "74d28de431d948e5abeca6084c49cff1":{
      "scriptId":"u24"},
    "25b34c02a37641368248f387bb28387f":{
      "scriptId":"u25"},
    "d95a6fc2c7474e3099f5d6e4166b3dbf":{
      "scriptId":"u26"},
    "cdd08a94387d49848758d742d09d07ab":{
      "scriptId":"u27"},
    "9bd062df7a7e4de299744a95f1cbf555":{
      "scriptId":"u28"},
    "fb7176ebba304749be59135c9c3e17e2":{
      "scriptId":"u29"},
    "938d68ca3d704969b60834235a6ac2af":{
      "scriptId":"u30"},
    "455c8a29f2cc43b9b9268b8021c83717":{
      "scriptId":"u31"},
    "3202c0eea1ab49f49a9d47c29ee67234":{
      "scriptId":"u32"},
    "45f4576797ba4dfb969eaaeffd90a460":{
      "scriptId":"u33"},
    "5c485d98f51a4a47ab6690466785244d":{
      "scriptId":"u34"},
    "f84cad4cd65f44e7bac82bdb0a671b32":{
      "scriptId":"u35"},
    "6f666a87df22415588f30bc99f64fa72":{
      "scriptId":"u36"},
    "abdb93d7066a46ce835b90ecb3db3002":{
      "scriptId":"u37"},
    "021c995d24564651b7dfc38a384703b0":{
      "scriptId":"u38"},
    "3176fde008f24617b05dd97ca820c651":{
      "scriptId":"u39"},
    "8188ca8fc9354eceaa075664b0c7b396":{
      "scriptId":"u40"},
    "0784af9a205a43e5a6ac012b2eaaba66":{
      "scriptId":"u41"},
    "39b01e0419fb4f50bf7a6c36ba94535e":{
      "scriptId":"u42"},
    "54c7fec940c64668bd9128bc12635ae9":{
      "scriptId":"u43"},
    "dcacaa1039d24e738578304b6e17dd3a":{
      "scriptId":"u44"},
    "39ca62b3a33b443da1732c02c67d61f6":{
      "scriptId":"u45"},
    "97b857c78f59450b91c1d6b1ce9234be":{
      "scriptId":"u46"},
    "c356cc3596c941e59aa9dc10994b7670":{
      "scriptId":"u47"},
    "72fa739bb5b2439d8e9d390afb444e3d":{
      "scriptId":"u48"},
    "6a852923ec064dbf9ff2969d1a2ade2a":{
      "scriptId":"u49"},
    "6f8115e6d27b4931b22cb4f9c39ec6c4":{
      "scriptId":"u50"},
    "8a202d998ecc4b6f9410154a80ac340b":{
      "scriptId":"u51"},
    "71c7d18f915943978586482bfddf4855":{
      "scriptId":"u52"},
    "7bb16fcfa5154010b040efb76a2bfb72":{
      "scriptId":"u53"},
    "c9c4d6d2a824462e81b93835ff7cf88c":{
      "scriptId":"u54"},
    "c7c96e86a0594d028816884a170fb6e6":{
      "scriptId":"u55"},
    "bf4d1ccc42c14225bea9353fc2e7cc38":{
      "scriptId":"u56"},
    "85779be9f2c04aeba48ae7e77e6efe07":{
      "scriptId":"u57"},
    "ac34d7c4872d4546969ae72a3d02ba9f":{
      "scriptId":"u58"},
    "c0bc06fadf7c41f88f07961c56f0cc52":{
      "scriptId":"u59"},
    "7d94f5192fae4a41b416761e9445f9e1":{
      "scriptId":"u60"},
    "9e8f1c1232844537a72c9bfe23435439":{
      "scriptId":"u61"},
    "d7d7e481f35d407fa925c939f01bd675":{
      "scriptId":"u62"},
    "ea5775eb20d6459a96463923f82b1062":{
      "scriptId":"u63"},
    "14f0e2340ab747b48dbf84e5b2250753":{
      "scriptId":"u64"},
    "a7fa69d6d8864c8aba94b7f84b3f1d66":{
      "scriptId":"u65"},
    "62e5cfe21b0d4be282af8193b09f7786":{
      "scriptId":"u66"},
    "4b1ffd247f09466e8065083cccb6ee0a":{
      "scriptId":"u67"},
    "f5685feb00394056845c3abfdf563ddf":{
      "scriptId":"u68"},
    "52bcd7d5de7f4a04aa8c720103ab5e2c":{
      "scriptId":"u69"},
    "3ee60b22057e4d00a251adb8feda68fa":{
      "scriptId":"u70"},
    "6930b3f417a44ad5937b9bfbba8317c2":{
      "scriptId":"u71"},
    "e1056eeb12514b38b5aa66b0ad238664":{
      "scriptId":"u72"},
    "ccefc98f74ec4ff3b549e8017817bcb0":{
      "scriptId":"u73"},
    "c1632e6b4fc046f78a70b890bb58b783":{
      "scriptId":"u74"},
    "bd0965957542481db37d3615ee385e1b":{
      "scriptId":"u75"},
    "68a624df893449e0a5f5754f6fd187ce":{
      "scriptId":"u76"},
    "7831828fe1c542fab5977b72d5ff2052":{
      "scriptId":"u77"},
    "f45428a17d624aa8ae7deeaf43c7bf9c":{
      "scriptId":"u78"},
    "398d27e653b34411aaba59f976dfdaa8":{
      "scriptId":"u79"},
    "4c489be7da3e479089bc326a5ef9083c":{
      "scriptId":"u80"},
    "986ae793a8ce4ee5878eddb8348d6b6b":{
      "scriptId":"u81"},
    "60c5f4f6523d47bd85f22a947e3a528c":{
      "scriptId":"u82"},
    "eee7d82d3b91474c90cb506b399eead4":{
      "scriptId":"u83"},
    "19860af0042a4c4390a03b60de809ff8":{
      "scriptId":"u84"},
    "4e1bf18e6d754843ba0ceea9f432d4d4":{
      "scriptId":"u85"},
    "e4cc5dfa6cb1479fab012b49d208fde2":{
      "scriptId":"u86"},
    "1719e26768c848a19c88166d5775b275":{
      "scriptId":"u87"},
    "2e92f6952ab24725a9aad1d57c76c249":{
      "scriptId":"u88"},
    "d1561270163f4096955a436649f19d06":{
      "scriptId":"u89"},
    "faff7176cb7948f9822c1735923dad5d":{
      "scriptId":"u90"},
    "962d5e2cdccc43db8c5b7d0261ef1845":{
      "scriptId":"u91"},
    "0bfd52c3a7114804a204d8d7b9950eba":{
      "scriptId":"u92"},
    "24335a4f82d44a1b8d2df3630e66be6b":{
      "scriptId":"u93"},
    "6570762b1010488ba42fc310aa6e2e97":{
      "scriptId":"u94"},
    "0c9670bf8de0420a9f9db85b4cb2c622":{
      "scriptId":"u95"},
    "c59a4093cea24a0584725ee961297ec6":{
      "scriptId":"u96"},
    "7a2485446d9346988920f87e7f1c4e89":{
      "scriptId":"u97"},
    "8d9794ea3d3e4302a5afd870b0ca264c":{
      "scriptId":"u98"},
    "ca87db4de3b748c599a1204b7aedeaff":{
      "scriptId":"u99"},
    "4eec94166af248f5a7176fe2908fa80c":{
      "scriptId":"u100"},
    "f5562d8fa19a4723bd6119d64a7e416c":{
      "scriptId":"u101"},
    "31453eec862145c3a8aea6f81ae33b72":{
      "scriptId":"u102"},
    "915f423893fa469bbf3195452d83f361":{
      "scriptId":"u103"},
    "e56f4051695c4c988056bf98c062e08c":{
      "scriptId":"u104"},
    "e5d184031fd44c9fa943c331ed26cb24":{
      "scriptId":"u105"},
    "b2502c65eaa14892962227b940a3e790":{
      "scriptId":"u106"},
    "af58ad46475d43e5a2aa87fc3bfdf385":{
      "scriptId":"u107"},
    "785e0123e7da4b1aadf33b34048ad7f7":{
      "scriptId":"u108"},
    "210a9f4db1b0431b8c44ab54d776475b":{
      "scriptId":"u109"}}});