$axure.loadCurrentPage({
  "url":"兑换页面.html",
  "generationDate":new Date(1448007539914.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"bohao"],
  "page":{
    "packageId":"14ed7074b4c9494abaa1230b0cfbe2ea",
    "type":"Axure:Page",
    "name":"兑换页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d59e02ecfba14626a7200ec7b28b9bb2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"93fd5d385bb2419698ca8d204db6bd4a"},
{
          "id":"e55e6c8318a94cd69b412b0004cd32b7",
          "label":"shouye",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":250,
              "height":430}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"983ad1f76e1649c491ab29813c9e5dfe",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"555e7ac60f5a4ffba98a8d1f40422d06",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dbb7a98a30234224957c3a75a858677f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"7a8b140d47fe401ebf8e3ec2e3562c57",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":98,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2cb5ae310d01473891aefaad71ec65f4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":98,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7441a1c479fa49999882840194baa102",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":7},
                    "size":{
                      "width":35,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"43b5cbeb60eb46cda00ebaec40acb03d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":7},
                        "size":{
                          "width":35,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 商品页面2",
                              "target":{
                                "targetType":"page",
                                "url":"商品页面2.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"314b36a5742047b5b8b1745a3494d1f7",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":8,
                      "y":37},
                    "size":{
                      "width":57,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b57f2759b75347afa0e29bb6cc672181",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":8,
                          "y":37},
                        "size":{
                          "width":57,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3fad6911a221441c9c5190176570f0e4",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":56},
                    "size":{
                      "width":250,
                      "height":54}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"54af90d42fb74c45a42cb1620da057cd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":56},
                        "size":{
                          "width":250,
                          "height":54}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/兑换页面/u14.png"}},
{
                  "id":"bea7fdb54fa54a3d8ede886836d2c02e",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":11,
                      "y":66},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8fefd17b7d104ee8afb08eb1d07feaa0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":11,
                          "y":66},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"01c77104f0e142bf875c3d468c552f15",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":11,
                      "y":88},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"81766729f60c4d33931681e692efd0c2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":11,
                          "y":88},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ece284d7e5f94eabb42e47b9a1e4c24d",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":64,
                      "y":66},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ad2812ba281b4cd1ad2ffd2f82fd4485",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":64,
                          "y":66},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6b8853ccb1864b3db9d7378d8f62ef4c",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":109,
                      "y":66},
                    "size":{
                      "width":78,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e105f005d4b04a15abea792e12bb3361",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":109,
                          "y":66},
                        "size":{
                          "width":78,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"788a6432937c4f4384e9715049b6cfe8",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":64,
                      "y":88},
                    "size":{
                      "width":156,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b942a6f6293e44c5abbe9a67ec29c6fd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":64,
                          "y":88},
                        "size":{
                          "width":156,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d1a29ce543af4a8bbbb5434a0ae73bb9",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":230,
                      "y":67},
                    "size":{
                      "width":20,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"65203e7bafd347a0b5e128f71bb30234",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":230,
                          "y":67},
                        "size":{
                          "width":20,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u15.png"}},
{
                  "id":"4b1a6b7901ad48408dba142c7a63b882",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":11,
                      "y":120},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"68939e242b6b4aa3b21a062e821e35b7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":11,
                          "y":120},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2fcbc954ae494314a383f906e4f3ff8f",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":250,
                      "height":230}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"15902ad19a2a4df990e118844f89617b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":150},
                        "size":{
                          "width":250,
                          "height":230}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/兑换页面/u30.png"}},
{
                  "id":"958051676c3b4a1190fa8729fe8d179f",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":11,
                      "y":160},
                    "size":{
                      "width":49,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a302d6c4e55438796663d7e72dbef6f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":11,
                          "y":160},
                        "size":{
                          "width":49,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/兑换页面/u32.png"}},
{
                  "id":"64a06bef8ca04e86ae73612c74e3ef15",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":70,
                      "y":160},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5256380352d142e4bc6439926e233446",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":70,
                          "y":160},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a4190206bc1f4e6987ffdc03e17ab205",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":195},
                    "size":{
                      "width":212,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/兑换页面/u36_line.png"}},
{
                  "id":"54fd22f9ca9e41de96e5cf0b71f5a68a",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":357},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"214061e6dfde44fa92a42448637a7073",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":357},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3dcb05da0638414ab982fd4cbdac95e7",
                  "label":"dj",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":215},
                    "size":{
                      "width":54,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"efde2d990e8343b4adeadf47a0b0b581",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":160,
                          "y":215},
                        "size":{
                          "width":54,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f4d0af3daa5d4ac7aaf04783f609383d",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":231},
                    "size":{
                      "width":212,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/兑换页面/u36_line.png"}},
{
                  "id":"b3c7df9e03fb4b3cb0cab46088fcafcc",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":249},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2859ee7f17fb453aa35a5297af35ae98",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":249},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b8f74b0229d247ad8fcb3e6006b4cb33",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":265},
                    "size":{
                      "width":212,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/兑换页面/u36_line.png"}},
{
                  "id":"6b9bf5a3cf7a4a0fa23071e74a7adb4b",
                  "label":"shuliang",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":184,
                      "y":241},
                    "size":{
                      "width":20,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"16b7c5ac778041d19bd5f96d91bb5b84",
                  "label":"+",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":214,
                      "y":245},
                    "size":{
                      "width":20,
                      "height":20},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c0a4702c52494b59aad7159862c0f5ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":214,
                          "y":245},
                        "size":{
                          "width":20,
                          "height":20},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1<br> (If 文字于 shuliang ≥ &quot;1&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":">=",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["6b9bf5a3cf7a4a0fa23071e74a7adb4b"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]}},
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 文字于 shuliang = &quot;[[sl+1]]&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetFormText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["6b9bf5a3cf7a4a0fa23071e74a7adb4b"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"[[sl+1]]",
                                        "localVariables":{
                                          "sl":{
                                            "exprType":"fcall",
                                            "functionName":"GetWidgetText",
                                            "arguments":[{
                                                "exprType":"pathLiteral",
                                                "isThis":false,
                                                "isFocused":false,
                                                "isTarget":false,
                                                "value":["6b9bf5a3cf7a4a0fa23071e74a7adb4b"]}]}},
                                        "stos":[{
                                            "sto":"binOp",
                                            "op":"+",
                                            "leftSTO":{
                                              "sto":"var",
                                              "name":"sl"},
                                            "rightSTO":{
                                              "computedType":"int",
                                              "sto":"literal",
                                              "value":1}}]}]}]}},
{
                              "action":"setFunction",
                              "description":"设置 文字于 zj = &quot;[[dj*sl]]&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["ea60fa1390be4f8ba7a790ce6653fce7"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"[[dj*sl]]",
                                        "localVariables":{
                                          "dj":{
                                            "exprType":"fcall",
                                            "functionName":"GetWidgetText",
                                            "arguments":[{
                                                "exprType":"pathLiteral",
                                                "isThis":false,
                                                "isFocused":false,
                                                "isTarget":false,
                                                "value":["3dcb05da0638414ab982fd4cbdac95e7"]}]},
                                          "sl":{
                                            "exprType":"fcall",
                                            "functionName":"GetWidgetText",
                                            "arguments":[{
                                                "exprType":"pathLiteral",
                                                "isThis":false,
                                                "isFocused":false,
                                                "isTarget":false,
                                                "value":["6b9bf5a3cf7a4a0fa23071e74a7adb4b"]}]}},
                                        "stos":[{
                                            "computedType":"int",
                                            "sto":"binOp",
                                            "op":"*",
                                            "leftSTO":{
                                              "sto":"var",
                                              "name":"dj"},
                                            "rightSTO":{
                                              "sto":"var",
                                              "name":"sl"}}]},
{
                                        "exprType":"booleanLiteral",
                                        "value":true}]}]}}]},
{
                          "description":"用例 2<br> (If 文字于 shuliang &lt; &quot;1&quot;)",
                          "isNewIfGroup":true,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"<",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["6b9bf5a3cf7a4a0fa23071e74a7adb4b"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]}},
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 文字于 shuliang = &quot;1&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetFormText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["6b9bf5a3cf7a4a0fa23071e74a7adb4b"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/兑换页面/__u46.png"}},
{
                  "id":"cc616cce20a849aa9a1404e06c42cd1a",
                  "label":"-",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":154,
                      "y":243.5},
                    "size":{
                      "width":20,
                      "height":20},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b46360d82e0d49e9910f25173324f70e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":154,
                          "y":243.5},
                        "size":{
                          "width":20,
                          "height":20},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1<br> (If 文字于 shuliang ≥ &quot;1&quot;)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":">=",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["6b9bf5a3cf7a4a0fa23071e74a7adb4b"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]}},
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 文字于 shuliang = &quot;[[sl-1]]&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetFormText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["6b9bf5a3cf7a4a0fa23071e74a7adb4b"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"[[sl-1]]",
                                        "localVariables":{
                                          "sl":{
                                            "exprType":"fcall",
                                            "functionName":"GetWidgetText",
                                            "arguments":[{
                                                "exprType":"pathLiteral",
                                                "isThis":false,
                                                "isFocused":false,
                                                "isTarget":false,
                                                "value":["6b9bf5a3cf7a4a0fa23071e74a7adb4b"]}]}},
                                        "stos":[{
                                            "computedType":"int",
                                            "sto":"binOp",
                                            "op":"-",
                                            "leftSTO":{
                                              "sto":"var",
                                              "name":"sl"},
                                            "rightSTO":{
                                              "computedType":"int",
                                              "sto":"literal",
                                              "value":1}}]}]}]}},
{
                              "action":"setFunction",
                              "description":"设置 文字于 zj = &quot;[[dj*sl]]&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetRichText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["ea60fa1390be4f8ba7a790ce6653fce7"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"[[dj*sl]]",
                                        "localVariables":{
                                          "dj":{
                                            "exprType":"fcall",
                                            "functionName":"GetWidgetText",
                                            "arguments":[{
                                                "exprType":"pathLiteral",
                                                "isThis":false,
                                                "isFocused":false,
                                                "isTarget":false,
                                                "value":["3dcb05da0638414ab982fd4cbdac95e7"]}]},
                                          "sl":{
                                            "exprType":"fcall",
                                            "functionName":"GetWidgetText",
                                            "arguments":[{
                                                "exprType":"pathLiteral",
                                                "isThis":false,
                                                "isFocused":false,
                                                "isTarget":false,
                                                "value":["6b9bf5a3cf7a4a0fa23071e74a7adb4b"]}]}},
                                        "stos":[{
                                            "computedType":"int",
                                            "sto":"binOp",
                                            "op":"*",
                                            "leftSTO":{
                                              "sto":"var",
                                              "name":"dj"},
                                            "rightSTO":{
                                              "sto":"var",
                                              "name":"sl"}}]},
{
                                        "exprType":"booleanLiteral",
                                        "value":true}]}]}}]},
{
                          "description":"用例 2<br> (If 文字于 shuliang &lt; &quot;1&quot;)",
                          "isNewIfGroup":true,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"<",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetWidgetText",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["6b9bf5a3cf7a4a0fa23071e74a7adb4b"]}]},
                            "rightExpr":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]}},
                          "actions":[{
                              "action":"setFunction",
                              "description":"设置 文字于 shuliang = &quot;1&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[{
                                    "exprType":"fcall",
                                    "functionName":"SetWidgetFormText",
                                    "arguments":[{
                                        "exprType":"pathLiteral",
                                        "isThis":false,
                                        "isFocused":false,
                                        "isTarget":false,
                                        "value":["6b9bf5a3cf7a4a0fa23071e74a7adb4b"]},
{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]}]}]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/兑换页面/__u46.png"}},
{
                  "id":"7a075bbeae11476284239cce8ae22add",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":282},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"580548b53c1d4f7a975b1571bf8dd162",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":282},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"92a1e7a4aedd4978a7c61f09994234cc",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"radioButton",
                  "styleType":"radioButton",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":134,
                      "y":311},
                    "size":{
                      "width":100,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"23406c0e3bc74ad681f7e582e8c0d520",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":134,
                          "y":311},
                        "size":{
                          "width":100,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"ba4afd75c2ad409c9c623edb6967b9c7",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"radioButton",
                  "styleType":"radioButton",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":134,
                      "y":282},
                    "size":{
                      "width":100,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0f78ebad423349e69fbc572d0f3da433",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":134,
                          "y":282},
                        "size":{
                          "width":100,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"d54d6acf108c4a1fb6394537dfd1353f",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":337},
                    "size":{
                      "width":212,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/兑换页面/u36_line.png"}},
{
                  "id":"ffed5999767d4543b522d13765e8e051",
                  "label":"zj",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":357},
                    "size":{
                      "width":54,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ea60fa1390be4f8ba7a790ce6653fce7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":160,
                          "y":357},
                        "size":{
                          "width":54,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1603cfb7478544788638ce05e4617570",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":215},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"974d6cde50a041d4862529689eb7326a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":215},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5ec10e3ca17645918b1d6e6e9c6980e1",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":28,
                      "y":390},
                    "size":{
                      "width":176,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"be929224ca11471790a13a7d6ca9d2c5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":28,
                          "y":390},
                        "size":{
                          "width":176,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/兑换页面/u61.png"}},
{
                  "id":"6e32426f94da48a5b9d3f3e69d07bb96",
                  "label":"",
                  "parentDynamicPanel":"e55e6c8318a94cd69b412b0004cd32b7",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":59},
                    "size":{
                      "width":250,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 收货地址",
                              "target":{
                                "targetType":"page",
                                "url":"收货地址.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"14bd04b35e7e4826b6e11c75d752824b",
          "label":"顶部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":40,
              "y":80},
            "size":{
              "width":250,
              "height":20},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bcbbaf77a094707b46ceaf1099709ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":40,
                  "y":80},
                "size":{
                  "width":250,
                  "height":20},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/顶部_u80.png"}},
{
          "id":"975d51dfc63547c3b3921f422feb9591",
          "label":"D",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":530},
            "size":{
              "width":356,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fa34c2975f6445a95732631ed3cf8bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":530},
                "size":{
                  "width":356,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u82.png"}},
{
          "id":"cfaec2e2381e43e1936a6ccb86ff5b69",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":2},
            "size":{
              "width":327,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5712c6f252274cf8b865b7fec55b1ecb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":2},
                "size":{
                  "width":327,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u84.png"}},
{
          "id":"2de77a34682e4a6d8df4a98c79e968fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":336,
              "height":2},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2df7490d4b784c0fa940ffd93bd60148",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":336,
                  "height":2},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u86.png"}}]}},
  "masters":{
    "93fd5d385bb2419698ca8d204db6bd4a":{
      "packageId":"93fd5d385bb2419698ca8d204db6bd4a",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2e194cf0c2b54c5680885a8df07da4e2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":336,
                "height":627}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0c76e3d052f04fcfb070a80a46e1e3f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":336,
                    "height":627}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u1.png"}},
{
            "id":"12b733eb02494e5a8662e96bcc215f5f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":100},
              "size":{
                "width":250,
                "height":430}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18c2b83789bc48f89e71a44ca19cb8ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":100},
                  "size":{
                    "width":250,
                    "height":430}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u3.png"}}]}}},
  "objectPaths":{
    "d59e02ecfba14626a7200ec7b28b9bb2":{
      "scriptId":"u0",
      "2e194cf0c2b54c5680885a8df07da4e2":{
        "scriptId":"u1"},
      "0c76e3d052f04fcfb070a80a46e1e3f9":{
        "scriptId":"u2"},
      "12b733eb02494e5a8662e96bcc215f5f":{
        "scriptId":"u3"},
      "18c2b83789bc48f89e71a44ca19cb8ae":{
        "scriptId":"u4"}},
    "e55e6c8318a94cd69b412b0004cd32b7":{
      "scriptId":"u5"},
    "555e7ac60f5a4ffba98a8d1f40422d06":{
      "scriptId":"u6"},
    "dbb7a98a30234224957c3a75a858677f":{
      "scriptId":"u7"},
    "7a8b140d47fe401ebf8e3ec2e3562c57":{
      "scriptId":"u8"},
    "2cb5ae310d01473891aefaad71ec65f4":{
      "scriptId":"u9"},
    "7441a1c479fa49999882840194baa102":{
      "scriptId":"u10"},
    "43b5cbeb60eb46cda00ebaec40acb03d":{
      "scriptId":"u11"},
    "314b36a5742047b5b8b1745a3494d1f7":{
      "scriptId":"u12"},
    "b57f2759b75347afa0e29bb6cc672181":{
      "scriptId":"u13"},
    "3fad6911a221441c9c5190176570f0e4":{
      "scriptId":"u14"},
    "54af90d42fb74c45a42cb1620da057cd":{
      "scriptId":"u15"},
    "bea7fdb54fa54a3d8ede886836d2c02e":{
      "scriptId":"u16"},
    "8fefd17b7d104ee8afb08eb1d07feaa0":{
      "scriptId":"u17"},
    "01c77104f0e142bf875c3d468c552f15":{
      "scriptId":"u18"},
    "81766729f60c4d33931681e692efd0c2":{
      "scriptId":"u19"},
    "ece284d7e5f94eabb42e47b9a1e4c24d":{
      "scriptId":"u20"},
    "ad2812ba281b4cd1ad2ffd2f82fd4485":{
      "scriptId":"u21"},
    "6b8853ccb1864b3db9d7378d8f62ef4c":{
      "scriptId":"u22"},
    "e105f005d4b04a15abea792e12bb3361":{
      "scriptId":"u23"},
    "788a6432937c4f4384e9715049b6cfe8":{
      "scriptId":"u24"},
    "b942a6f6293e44c5abbe9a67ec29c6fd":{
      "scriptId":"u25"},
    "d1a29ce543af4a8bbbb5434a0ae73bb9":{
      "scriptId":"u26"},
    "65203e7bafd347a0b5e128f71bb30234":{
      "scriptId":"u27"},
    "4b1a6b7901ad48408dba142c7a63b882":{
      "scriptId":"u28"},
    "68939e242b6b4aa3b21a062e821e35b7":{
      "scriptId":"u29"},
    "2fcbc954ae494314a383f906e4f3ff8f":{
      "scriptId":"u30"},
    "15902ad19a2a4df990e118844f89617b":{
      "scriptId":"u31"},
    "958051676c3b4a1190fa8729fe8d179f":{
      "scriptId":"u32"},
    "4a302d6c4e55438796663d7e72dbef6f":{
      "scriptId":"u33"},
    "64a06bef8ca04e86ae73612c74e3ef15":{
      "scriptId":"u34"},
    "5256380352d142e4bc6439926e233446":{
      "scriptId":"u35"},
    "a4190206bc1f4e6987ffdc03e17ab205":{
      "scriptId":"u36"},
    "54fd22f9ca9e41de96e5cf0b71f5a68a":{
      "scriptId":"u37"},
    "214061e6dfde44fa92a42448637a7073":{
      "scriptId":"u38"},
    "3dcb05da0638414ab982fd4cbdac95e7":{
      "scriptId":"u39"},
    "efde2d990e8343b4adeadf47a0b0b581":{
      "scriptId":"u40"},
    "f4d0af3daa5d4ac7aaf04783f609383d":{
      "scriptId":"u41"},
    "b3c7df9e03fb4b3cb0cab46088fcafcc":{
      "scriptId":"u42"},
    "2859ee7f17fb453aa35a5297af35ae98":{
      "scriptId":"u43"},
    "b8f74b0229d247ad8fcb3e6006b4cb33":{
      "scriptId":"u44"},
    "6b9bf5a3cf7a4a0fa23071e74a7adb4b":{
      "scriptId":"u45"},
    "16b7c5ac778041d19bd5f96d91bb5b84":{
      "scriptId":"u46"},
    "c0a4702c52494b59aad7159862c0f5ef":{
      "scriptId":"u47"},
    "cc616cce20a849aa9a1404e06c42cd1a":{
      "scriptId":"u48"},
    "b46360d82e0d49e9910f25173324f70e":{
      "scriptId":"u49"},
    "7a075bbeae11476284239cce8ae22add":{
      "scriptId":"u50"},
    "580548b53c1d4f7a975b1571bf8dd162":{
      "scriptId":"u51"},
    "92a1e7a4aedd4978a7c61f09994234cc":{
      "scriptId":"u52"},
    "23406c0e3bc74ad681f7e582e8c0d520":{
      "scriptId":"u53"},
    "ba4afd75c2ad409c9c623edb6967b9c7":{
      "scriptId":"u54"},
    "0f78ebad423349e69fbc572d0f3da433":{
      "scriptId":"u55"},
    "d54d6acf108c4a1fb6394537dfd1353f":{
      "scriptId":"u56"},
    "ffed5999767d4543b522d13765e8e051":{
      "scriptId":"u57"},
    "ea60fa1390be4f8ba7a790ce6653fce7":{
      "scriptId":"u58"},
    "1603cfb7478544788638ce05e4617570":{
      "scriptId":"u59"},
    "974d6cde50a041d4862529689eb7326a":{
      "scriptId":"u60"},
    "5ec10e3ca17645918b1d6e6e9c6980e1":{
      "scriptId":"u61"},
    "be929224ca11471790a13a7d6ca9d2c5":{
      "scriptId":"u62"},
    "6e32426f94da48a5b9d3f3e69d07bb96":{
      "scriptId":"u63"},
    "14bd04b35e7e4826b6e11c75d752824b":{
      "scriptId":"u64"},
    "9bcbbaf77a094707b46ceaf1099709ec":{
      "scriptId":"u65"},
    "975d51dfc63547c3b3921f422feb9591":{
      "scriptId":"u66"},
    "4fa34c2975f6445a95732631ed3cf8bc":{
      "scriptId":"u67"},
    "cfaec2e2381e43e1936a6ccb86ff5b69":{
      "scriptId":"u68"},
    "5712c6f252274cf8b865b7fec55b1ecb":{
      "scriptId":"u69"},
    "2de77a34682e4a6d8df4a98c79e968fb":{
      "scriptId":"u70"},
    "2df7490d4b784c0fa940ffd93bd60148":{
      "scriptId":"u71"}}});