$axure.loadCurrentPage({
  "url":"看红包.html",
  "generationDate":new Date(1448007541058.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"bohao"],
  "page":{
    "packageId":"ac864046625b40978e971c3c45e3067f",
    "type":"Axure:Page",
    "name":"看红包",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fad67a6ec4b544d995743916a3e4eb95",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"93fd5d385bb2419698ca8d204db6bd4a"},
{
          "id":"20862f026fe54c7e8cc438bfab561e13",
          "label":"kanhongbao",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":250,
              "height":430}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"86a91f7ec02b465ca5757366d3bcf64c",
              "label":"商品",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ca2dc3869f3e4c3a9bff0fa93b1bada3",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f7a6cef7679f4253bb9233710bcfee4f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"7078c0bd8fb54032810233af126a87ca",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":98,
                      "y":7},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f081b9bc693243139cf54bf03fff1734",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":98,
                          "y":7},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"673c0f8ed1684736b37aa2447964ebc6",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":7},
                    "size":{
                      "width":35,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b1d745118c3945b0a3417207742bbd6e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":7},
                        "size":{
                          "width":35,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"27aeb78edcda494db6a710a50da7204d",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"91a21a32469f4f529af0cd0f87b850e8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"84e3c23849ae4bb08a2458f17930e02d",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":37},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c62c260173dc4d74aa12c01906d004f0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":37},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"41374a28f13f498283551cefb40f2b7e",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":185,
                      "y":37},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3ab118e0f329426ab74c13612c28d76c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":185,
                          "y":37},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4e09ebf2318b4eb389a775d60d8bbfa9",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":250,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"12b9918dc9bc477b89c7e591ff3e8f1a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":80},
                        "size":{
                          "width":250,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u87.png"}},
{
                  "id":"46ee3da24f934e909db47cddde45d8b5",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":90},
                    "size":{
                      "width":53,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6349545b216b4002b395b4f233ce4d25",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":90},
                        "size":{
                          "width":53,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/抢红包/u20.png"}},
{
                  "id":"7d6efc67eda549d986c1a0de8c55d585",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":71,
                      "y":90},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"adfad5f67f834c0291c643c9de0f9947",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":71,
                          "y":90},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"33e661b07fae4091b023011ecd6dc03d",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":71,
                      "y":124},
                    "size":{
                      "width":107,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6180e6d1954f4d99b022ac35acebcc6c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":71,
                          "y":124},
                        "size":{
                          "width":107,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"60fbc2a0c2814363974da6bcf7a61f61",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":180},
                    "size":{
                      "width":250,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7931108969904aefb2e0bd5baa8efd5a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":180},
                        "size":{
                          "width":250,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u87.png"}},
{
                  "id":"e0c83d6a4b924c6ab37ed8300663738a",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":190},
                    "size":{
                      "width":53,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ae1bc8b24b6f46a68e1403b227b9843f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":190},
                        "size":{
                          "width":53,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/抢红包/u20.png"}},
{
                  "id":"8c857627fc204158a96456e18f83c70e",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":71,
                      "y":190},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fd05ad47a7ff4f9aa40d6aa5aa6eb630",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":71,
                          "y":190},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e116cfc1de3543adb023eb6c908cb6bc",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":71,
                      "y":224},
                    "size":{
                      "width":107,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9333ba21dfe341e38f13cc78d38409fd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":71,
                          "y":224},
                        "size":{
                          "width":107,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3f8e5ab9eef24b0f89ad8e128f173559",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":280},
                    "size":{
                      "width":250,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1387a1b8ca804fdf9f72cd9a5ba8e1b3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":280},
                        "size":{
                          "width":250,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u87.png"}},
{
                  "id":"9f9617c6a38340ea81d7fb79f34e243f",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":290},
                    "size":{
                      "width":53,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b2a25832d80945ffbd772287e46afa6f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":290},
                        "size":{
                          "width":53,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/抢红包/u20.png"}},
{
                  "id":"ce7a5feea6644d03ba2457b23aad4d3a",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":71,
                      "y":290},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a97bee3e75647e39274bd2bb7bb9c17",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":71,
                          "y":290},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"df122dd76ecc4e2886099a65fbeaa107",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":71,
                      "y":324},
                    "size":{
                      "width":107,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ca9382a8da024967a6e2588cb9c151ee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":71,
                          "y":324},
                        "size":{
                          "width":107,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9df1493fd8824a9aa80fa3f9c37590e8",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":250,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 看红包广告",
                              "target":{
                                "targetType":"page",
                                "url":"看红包广告.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"a0bfef115fe3499a9a7218459bc9f3c5",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":180},
                    "size":{
                      "width":250,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 看红包广告",
                              "target":{
                                "targetType":"page",
                                "url":"看红包广告.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true},
{
                  "id":"a2d287e616eb4b37bcb085bb879db6dd",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":280},
                    "size":{
                      "width":250,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 看红包广告",
                              "target":{
                                "targetType":"page",
                                "url":"看红包广告.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"1ccb84713a1d491b96862186faf1beaf",
          "label":"顶部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":40,
              "y":80},
            "size":{
              "width":250,
              "height":20},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dee70deb408484b822721c7dc170669",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":40,
                  "y":80},
                "size":{
                  "width":250,
                  "height":20},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/顶部_u80.png"}},
{
          "id":"47fa72f76dc94e2285606d6b63b8dfd3",
          "label":"D",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":530},
            "size":{
              "width":356,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c4e570237c6444f8d1af81b767eee9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":530},
                "size":{
                  "width":356,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u82.png"}},
{
          "id":"c015e55594634d04a5ae937567f04290",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":2},
            "size":{
              "width":327,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e777dd8bbe704135a3780122853a11da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":2},
                "size":{
                  "width":327,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u84.png"}}]}},
  "masters":{
    "93fd5d385bb2419698ca8d204db6bd4a":{
      "packageId":"93fd5d385bb2419698ca8d204db6bd4a",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2e194cf0c2b54c5680885a8df07da4e2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":336,
                "height":627}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0c76e3d052f04fcfb070a80a46e1e3f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":336,
                    "height":627}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u1.png"}},
{
            "id":"12b733eb02494e5a8662e96bcc215f5f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":100},
              "size":{
                "width":250,
                "height":430}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18c2b83789bc48f89e71a44ca19cb8ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":100},
                  "size":{
                    "width":250,
                    "height":430}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u3.png"}}]}}},
  "objectPaths":{
    "fad67a6ec4b544d995743916a3e4eb95":{
      "scriptId":"u0",
      "2e194cf0c2b54c5680885a8df07da4e2":{
        "scriptId":"u1"},
      "0c76e3d052f04fcfb070a80a46e1e3f9":{
        "scriptId":"u2"},
      "12b733eb02494e5a8662e96bcc215f5f":{
        "scriptId":"u3"},
      "18c2b83789bc48f89e71a44ca19cb8ae":{
        "scriptId":"u4"}},
    "20862f026fe54c7e8cc438bfab561e13":{
      "scriptId":"u5"},
    "ca2dc3869f3e4c3a9bff0fa93b1bada3":{
      "scriptId":"u6"},
    "f7a6cef7679f4253bb9233710bcfee4f":{
      "scriptId":"u7"},
    "7078c0bd8fb54032810233af126a87ca":{
      "scriptId":"u8"},
    "f081b9bc693243139cf54bf03fff1734":{
      "scriptId":"u9"},
    "673c0f8ed1684736b37aa2447964ebc6":{
      "scriptId":"u10"},
    "b1d745118c3945b0a3417207742bbd6e":{
      "scriptId":"u11"},
    "27aeb78edcda494db6a710a50da7204d":{
      "scriptId":"u12"},
    "91a21a32469f4f529af0cd0f87b850e8":{
      "scriptId":"u13"},
    "84e3c23849ae4bb08a2458f17930e02d":{
      "scriptId":"u14"},
    "c62c260173dc4d74aa12c01906d004f0":{
      "scriptId":"u15"},
    "41374a28f13f498283551cefb40f2b7e":{
      "scriptId":"u16"},
    "3ab118e0f329426ab74c13612c28d76c":{
      "scriptId":"u17"},
    "4e09ebf2318b4eb389a775d60d8bbfa9":{
      "scriptId":"u18"},
    "12b9918dc9bc477b89c7e591ff3e8f1a":{
      "scriptId":"u19"},
    "46ee3da24f934e909db47cddde45d8b5":{
      "scriptId":"u20"},
    "6349545b216b4002b395b4f233ce4d25":{
      "scriptId":"u21"},
    "7d6efc67eda549d986c1a0de8c55d585":{
      "scriptId":"u22"},
    "adfad5f67f834c0291c643c9de0f9947":{
      "scriptId":"u23"},
    "33e661b07fae4091b023011ecd6dc03d":{
      "scriptId":"u24"},
    "6180e6d1954f4d99b022ac35acebcc6c":{
      "scriptId":"u25"},
    "60fbc2a0c2814363974da6bcf7a61f61":{
      "scriptId":"u26"},
    "7931108969904aefb2e0bd5baa8efd5a":{
      "scriptId":"u27"},
    "e0c83d6a4b924c6ab37ed8300663738a":{
      "scriptId":"u28"},
    "ae1bc8b24b6f46a68e1403b227b9843f":{
      "scriptId":"u29"},
    "8c857627fc204158a96456e18f83c70e":{
      "scriptId":"u30"},
    "fd05ad47a7ff4f9aa40d6aa5aa6eb630":{
      "scriptId":"u31"},
    "e116cfc1de3543adb023eb6c908cb6bc":{
      "scriptId":"u32"},
    "9333ba21dfe341e38f13cc78d38409fd":{
      "scriptId":"u33"},
    "3f8e5ab9eef24b0f89ad8e128f173559":{
      "scriptId":"u34"},
    "1387a1b8ca804fdf9f72cd9a5ba8e1b3":{
      "scriptId":"u35"},
    "9f9617c6a38340ea81d7fb79f34e243f":{
      "scriptId":"u36"},
    "b2a25832d80945ffbd772287e46afa6f":{
      "scriptId":"u37"},
    "ce7a5feea6644d03ba2457b23aad4d3a":{
      "scriptId":"u38"},
    "7a97bee3e75647e39274bd2bb7bb9c17":{
      "scriptId":"u39"},
    "df122dd76ecc4e2886099a65fbeaa107":{
      "scriptId":"u40"},
    "ca9382a8da024967a6e2588cb9c151ee":{
      "scriptId":"u41"},
    "9df1493fd8824a9aa80fa3f9c37590e8":{
      "scriptId":"u42"},
    "a0bfef115fe3499a9a7218459bc9f3c5":{
      "scriptId":"u43"},
    "a2d287e616eb4b37bcb085bb879db6dd":{
      "scriptId":"u44"},
    "1ccb84713a1d491b96862186faf1beaf":{
      "scriptId":"u45"},
    "9dee70deb408484b822721c7dc170669":{
      "scriptId":"u46"},
    "47fa72f76dc94e2285606d6b63b8dfd3":{
      "scriptId":"u47"},
    "3c4e570237c6444f8d1af81b767eee9d":{
      "scriptId":"u48"},
    "c015e55594634d04a5ae937567f04290":{
      "scriptId":"u49"},
    "e777dd8bbe704135a3780122853a11da":{
      "scriptId":"u50"}}});