$axure.loadCurrentPage({
  "url":"个人资料.html",
  "generationDate":new Date(1448007539538.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"bohao"],
  "page":{
    "packageId":"63b2ba2e2f2946148b4ed65c8e0d7e60",
    "type":"Axure:Page",
    "name":"个人资料",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2457f00bdbb340e7a98d442e4c7ef03a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"93fd5d385bb2419698ca8d204db6bd4a"},
{
          "id":"f740daef314a4998be39ad98f35081b6",
          "label":"个人资料",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":250,
              "height":430}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c0e8ea210d344493a8b0a68325591d9d",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cd56c3ca38cf425381a4d22a6d182689",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"46cf2e3d32b4411482bfff0f8c98f4e8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"27e3faef69da4fde965794daaf477090",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":98,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eea4012712ec4a0286a371c024df2697",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":98,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"689b83d3600b4aa29569d763ca7cfa71",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":7},
                    "size":{
                      "width":35,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"18f39deacbef421a8111f11983050ed9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":7},
                        "size":{
                          "width":35,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 个人中心",
                              "target":{
                                "targetType":"page",
                                "url":"个人中心.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5151ec004f7640e7abb0c0ca63144867",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":49},
                    "size":{
                      "width":250,
                      "height":51},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c623bfce6649431a9a783ba99ac75ea8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":49},
                        "size":{
                          "width":250,
                          "height":51},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人资料/u12.png"}},
{
                  "id":"761866753a8f4ebda10ba17a304e751e",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"400",
                    "location":{
                      "x":17,
                      "y":65},
                    "size":{
                      "width":33,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b281002814242fe8e9f5ca2a39f0a50",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"400",
                        "location":{
                          "x":17,
                          "y":65},
                        "size":{
                          "width":33,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8a9f32fd0a654ac5ab9e5d0c325b0577",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":184,
                      "y":52},
                    "size":{
                      "width":46,
                      "height":45},
                    "cornerRadiusTopLeft":"43"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"73ff4a8c9c3d4779b11e2ff603fac3af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":184,
                          "y":52},
                        "size":{
                          "width":46,
                          "height":45},
                        "cornerRadiusTopLeft":"43"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u7.png"}},
{
                  "id":"64fdfbfede2e415c8452490c8b3fdeec",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":230,
                      "y":62},
                    "size":{
                      "width":18,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2426d271b7044eca84d3795e98989710",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":230,
                          "y":62},
                        "size":{
                          "width":18,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u15.png"}},
{
                  "id":"a6a0dcc7e6204eb686895474845dd5cc",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":110},
                    "size":{
                      "width":250,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"edfdb9137cbe4c26975fadf465c39f50",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":110},
                        "size":{
                          "width":250,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人资料/u20.png"}},
{
                  "id":"4f94806793e64876bad11842c034c606",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"400",
                    "location":{
                      "x":17,
                      "y":116},
                    "size":{
                      "width":33,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9e715b4d1d6e4666bb40e1ecb216373b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"400",
                        "location":{
                          "x":17,
                          "y":116},
                        "size":{
                          "width":33,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2535450cf8374000ad21ed07c189e3d0",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":191,
                      "y":118},
                    "size":{
                      "width":29,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6c7db71daf9a49f1a3e8facf21d41ca2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":191,
                          "y":118},
                        "size":{
                          "width":29,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3eaff89cee9c411b8dcdf181359f7388",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":230,
                      "y":119},
                    "size":{
                      "width":18,
                      "height":13}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c52045cc20764a10a1d22957ad93a4f1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":230,
                          "y":119},
                        "size":{
                          "width":18,
                          "height":13}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u15.png"}},
{
                  "id":"61520104e6f14a968f806085d1b364a0",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":250,
                      "height":130},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2bc8c36c29734620b6571ecf78638497",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":150},
                        "size":{
                          "width":250,
                          "height":130},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人资料/u28.png"}},
{
                  "id":"c806e17581984b389295e8c15e11a3cf",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"400",
                    "location":{
                      "x":17,
                      "y":160},
                    "size":{
                      "width":33,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c013c10cc6e44c698cbdec51155a8016",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"400",
                        "location":{
                          "x":17,
                          "y":160},
                        "size":{
                          "width":33,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cd2295e5c85b46448e4666713be95dd1",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"400",
                    "location":{
                      "x":17,
                      "y":189},
                    "size":{
                      "width":33,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"acb18d50b5e84224bf511e0faf4bc6bd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"400",
                        "location":{
                          "x":17,
                          "y":189},
                        "size":{
                          "width":33,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4b404042e421492c860c6c51648c177e",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"400",
                    "location":{
                      "x":17,
                      "y":218},
                    "size":{
                      "width":33,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"08b01058f885440fb8d4a46077f909ab",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"400",
                        "location":{
                          "x":17,
                          "y":218},
                        "size":{
                          "width":33,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4029379cc5094919a2f4ab27963f48d0",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontSize":"16px",
                    "fontWeight":"400",
                    "location":{
                      "x":17,
                      "y":247},
                    "size":{
                      "width":33,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"253d63870cbb4997b6e0278afd0fc286",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Normal', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"400",
                        "location":{
                          "x":17,
                          "y":247},
                        "size":{
                          "width":33,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"871f84e572104e329e8e69b2fec1e21c",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":179},
                    "size":{
                      "width":250,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/个人资料/u38_line.png"}},
{
                  "id":"7382775f76a644768729f1fd6f71c36c",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":208},
                    "size":{
                      "width":250,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/个人资料/u38_line.png"}},
{
                  "id":"e26ef59f472d4e7680e38f8aa63d3876",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":237},
                    "size":{
                      "width":250,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/个人资料/u38_line.png"}},
{
                  "id":"14636ab517ea4c548a76fa8f24412b2f",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":162},
                    "size":{
                      "width":78,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"61508caf24784f48a5e407a85454e3af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":160,
                          "y":162},
                        "size":{
                          "width":78,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"25ab79ddeae04675826d1242ae520e16",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":192,
                      "y":192},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cc94897153dc41aa83d40a0d45f4806a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":192,
                          "y":192},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"da6119f517a949de9f693399ff56c237",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":193,
                      "y":221},
                    "size":{
                      "width":14,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bf5d7c23849f49c9b5b0f51057530e1f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":193,
                          "y":221},
                        "size":{
                          "width":14,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c603390b11fb4cf19d66227ae9f7c311",
                  "label":"",
                  "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":146,
                      "y":250},
                    "size":{
                      "width":92,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a4e26318f053495cb1c411f0f7021e22",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f740daef314a4998be39ad98f35081b6",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":146,
                          "y":250},
                        "size":{
                          "width":92,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "93fd5d385bb2419698ca8d204db6bd4a":{
      "packageId":"93fd5d385bb2419698ca8d204db6bd4a",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2e194cf0c2b54c5680885a8df07da4e2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":336,
                "height":627}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0c76e3d052f04fcfb070a80a46e1e3f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":336,
                    "height":627}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u1.png"}},
{
            "id":"12b733eb02494e5a8662e96bcc215f5f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":100},
              "size":{
                "width":250,
                "height":430}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18c2b83789bc48f89e71a44ca19cb8ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":100},
                  "size":{
                    "width":250,
                    "height":430}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u3.png"}}]}}},
  "objectPaths":{
    "2457f00bdbb340e7a98d442e4c7ef03a":{
      "scriptId":"u0",
      "2e194cf0c2b54c5680885a8df07da4e2":{
        "scriptId":"u1"},
      "0c76e3d052f04fcfb070a80a46e1e3f9":{
        "scriptId":"u2"},
      "12b733eb02494e5a8662e96bcc215f5f":{
        "scriptId":"u3"},
      "18c2b83789bc48f89e71a44ca19cb8ae":{
        "scriptId":"u4"}},
    "f740daef314a4998be39ad98f35081b6":{
      "scriptId":"u5"},
    "cd56c3ca38cf425381a4d22a6d182689":{
      "scriptId":"u6"},
    "46cf2e3d32b4411482bfff0f8c98f4e8":{
      "scriptId":"u7"},
    "27e3faef69da4fde965794daaf477090":{
      "scriptId":"u8"},
    "eea4012712ec4a0286a371c024df2697":{
      "scriptId":"u9"},
    "689b83d3600b4aa29569d763ca7cfa71":{
      "scriptId":"u10"},
    "18f39deacbef421a8111f11983050ed9":{
      "scriptId":"u11"},
    "5151ec004f7640e7abb0c0ca63144867":{
      "scriptId":"u12"},
    "c623bfce6649431a9a783ba99ac75ea8":{
      "scriptId":"u13"},
    "761866753a8f4ebda10ba17a304e751e":{
      "scriptId":"u14"},
    "4b281002814242fe8e9f5ca2a39f0a50":{
      "scriptId":"u15"},
    "8a9f32fd0a654ac5ab9e5d0c325b0577":{
      "scriptId":"u16"},
    "73ff4a8c9c3d4779b11e2ff603fac3af":{
      "scriptId":"u17"},
    "64fdfbfede2e415c8452490c8b3fdeec":{
      "scriptId":"u18"},
    "2426d271b7044eca84d3795e98989710":{
      "scriptId":"u19"},
    "a6a0dcc7e6204eb686895474845dd5cc":{
      "scriptId":"u20"},
    "edfdb9137cbe4c26975fadf465c39f50":{
      "scriptId":"u21"},
    "4f94806793e64876bad11842c034c606":{
      "scriptId":"u22"},
    "9e715b4d1d6e4666bb40e1ecb216373b":{
      "scriptId":"u23"},
    "2535450cf8374000ad21ed07c189e3d0":{
      "scriptId":"u24"},
    "6c7db71daf9a49f1a3e8facf21d41ca2":{
      "scriptId":"u25"},
    "3eaff89cee9c411b8dcdf181359f7388":{
      "scriptId":"u26"},
    "c52045cc20764a10a1d22957ad93a4f1":{
      "scriptId":"u27"},
    "61520104e6f14a968f806085d1b364a0":{
      "scriptId":"u28"},
    "2bc8c36c29734620b6571ecf78638497":{
      "scriptId":"u29"},
    "c806e17581984b389295e8c15e11a3cf":{
      "scriptId":"u30"},
    "c013c10cc6e44c698cbdec51155a8016":{
      "scriptId":"u31"},
    "cd2295e5c85b46448e4666713be95dd1":{
      "scriptId":"u32"},
    "acb18d50b5e84224bf511e0faf4bc6bd":{
      "scriptId":"u33"},
    "4b404042e421492c860c6c51648c177e":{
      "scriptId":"u34"},
    "08b01058f885440fb8d4a46077f909ab":{
      "scriptId":"u35"},
    "4029379cc5094919a2f4ab27963f48d0":{
      "scriptId":"u36"},
    "253d63870cbb4997b6e0278afd0fc286":{
      "scriptId":"u37"},
    "871f84e572104e329e8e69b2fec1e21c":{
      "scriptId":"u38"},
    "7382775f76a644768729f1fd6f71c36c":{
      "scriptId":"u39"},
    "e26ef59f472d4e7680e38f8aa63d3876":{
      "scriptId":"u40"},
    "14636ab517ea4c548a76fa8f24412b2f":{
      "scriptId":"u41"},
    "61508caf24784f48a5e407a85454e3af":{
      "scriptId":"u42"},
    "25ab79ddeae04675826d1242ae520e16":{
      "scriptId":"u43"},
    "cc94897153dc41aa83d40a0d45f4806a":{
      "scriptId":"u44"},
    "da6119f517a949de9f693399ff56c237":{
      "scriptId":"u45"},
    "bf5d7c23849f49c9b5b0f51057530e1f":{
      "scriptId":"u46"},
    "c603390b11fb4cf19d66227ae9f7c311":{
      "scriptId":"u47"},
    "a4e26318f053495cb1c411f0f7021e22":{
      "scriptId":"u48"}}});