$axure.loadCurrentPage({
  "url":"玩红包.html",
  "generationDate":new Date(1448007541180.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"bohao"],
  "page":{
    "packageId":"f12e3b96bf3e45aab3f867c65d7e1853",
    "type":"Axure:Page",
    "name":"玩红包",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fad67a6ec4b544d995743916a3e4eb95",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"93fd5d385bb2419698ca8d204db6bd4a"},
{
          "id":"20862f026fe54c7e8cc438bfab561e13",
          "label":"kanhongbao",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":250,
              "height":430}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"86a91f7ec02b465ca5757366d3bcf64c",
              "label":"商品",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ca2dc3869f3e4c3a9bff0fa93b1bada3",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f7a6cef7679f4253bb9233710bcfee4f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"7078c0bd8fb54032810233af126a87ca",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":98,
                      "y":7},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f081b9bc693243139cf54bf03fff1734",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":98,
                          "y":7},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"673c0f8ed1684736b37aa2447964ebc6",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":7},
                    "size":{
                      "width":35,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b1d745118c3945b0a3417207742bbd6e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":7},
                        "size":{
                          "width":35,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"27aeb78edcda494db6a710a50da7204d",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"91a21a32469f4f529af0cd0f87b850e8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"84e3c23849ae4bb08a2458f17930e02d",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":37},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c62c260173dc4d74aa12c01906d004f0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":37},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"41374a28f13f498283551cefb40f2b7e",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":185,
                      "y":37},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3ab118e0f329426ab74c13612c28d76c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":185,
                          "y":37},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4e09ebf2318b4eb389a775d60d8bbfa9",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":130},
                    "size":{
                      "width":250,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"12b9918dc9bc477b89c7e591ff3e8f1a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":130},
                        "size":{
                          "width":250,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u87.png"}},
{
                  "id":"33e661b07fae4091b023011ecd6dc03d",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":64,
                      "y":183},
                    "size":{
                      "width":99,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6180e6d1954f4d99b022ac35acebcc6c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":64,
                          "y":183},
                        "size":{
                          "width":99,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8c857627fc204158a96456e18f83c70e",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":64,
                      "y":140},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fd05ad47a7ff4f9aa40d6aa5aa6eb630",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":64,
                          "y":140},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0d969cf94b324ca9a4b749fb8bc8e864",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":70},
                    "size":{
                      "width":250,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1db295b409d2412abdbd53caad7443cb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":70},
                        "size":{
                          "width":250,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/玩红包/u24.png"}},
{
                  "id":"92e1308dea184e129f24b1e4a311b4b1",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":74},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a4b5d78d790b40d08f2075e53577d3ee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":74},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d319c85582a44abd947b7b59a151c232",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "location":{
                      "x":15,
                      "y":90},
                    "size":{
                      "width":222,
                      "height":26}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dae314e7cab5462792022f3f4e924b58",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "location":{
                          "x":15,
                          "y":90},
                        "size":{
                          "width":222,
                          "height":26}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a79639fa63eb4e62935dee445928e38d",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":135},
                    "size":{
                      "width":46,
                      "height":45},
                    "cornerRadiusTopLeft":"43"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bd1308f1768e4c749af3637f54465cce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":135},
                        "size":{
                          "width":46,
                          "height":45},
                        "cornerRadiusTopLeft":"43"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u7.png"}},
{
                  "id":"11fa806876124ff5aaeb409b3c614315",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "location":{
                      "x":64,
                      "y":160},
                    "size":{
                      "width":140,
                      "height":13}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e8a09a39b981428a9a4b84aa10c70b60",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "location":{
                          "x":64,
                          "y":160},
                        "size":{
                          "width":140,
                          "height":13}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"82dd593e71ea4a03b302427ee67cb413",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":173,
                      "y":180},
                    "size":{
                      "width":64,
                      "height":19},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"331e1daea782483484557b12f1083f28",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":173,
                          "y":180},
                        "size":{
                          "width":64,
                          "height":19},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/玩红包/u34.png"}},
{
                  "id":"0508289cd85b45b4bf1d6d12f7bde3d4",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":220},
                    "size":{
                      "width":250,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2fc6e6b69ab044c8b3bb9030792bcea0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":220},
                        "size":{
                          "width":250,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u87.png"}},
{
                  "id":"b93c9e1951be4c5d81bdadab44c16f7a",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":64,
                      "y":273},
                    "size":{
                      "width":99,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9efa07ce3b934a8cacb8e23e4b8f7ca0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":64,
                          "y":273},
                        "size":{
                          "width":99,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"729bcb9523e64b7b9a8a6bbb2ca35c6f",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":64,
                      "y":230},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"407411a9f04943f587f6e9673b4896d2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":64,
                          "y":230},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"caf640d54be144599956c961aa641af2",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":225},
                    "size":{
                      "width":46,
                      "height":45},
                    "cornerRadiusTopLeft":"43"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aa6be57a423241408e39a064890b6be0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":225},
                        "size":{
                          "width":46,
                          "height":45},
                        "cornerRadiusTopLeft":"43"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u7.png"}},
{
                  "id":"48541a205f034c11906619f59a7fe776",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "location":{
                      "x":64,
                      "y":250},
                    "size":{
                      "width":140,
                      "height":13}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a728ae7052b4fd48fb7db81d954c5de",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "location":{
                          "x":64,
                          "y":250},
                        "size":{
                          "width":140,
                          "height":13}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f6064edb37cd4708a8949e241caf8ad2",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":173,
                      "y":270},
                    "size":{
                      "width":64,
                      "height":19},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f4ed28e5b74f45d2906b9102c5fa8e36",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":173,
                          "y":270},
                        "size":{
                          "width":64,
                          "height":19},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/玩红包/u34.png"}},
{
                  "id":"7a5ecede76d34aefa676f6a7173e076a",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":310},
                    "size":{
                      "width":250,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"445cb227994c4ca084a45f7ae035e4db",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":310},
                        "size":{
                          "width":250,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u87.png"}},
{
                  "id":"6daaef33b88b426fb1873c6df4508564",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":64,
                      "y":363},
                    "size":{
                      "width":99,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ab8fac21562b4a4abc79899902eef327",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":64,
                          "y":363},
                        "size":{
                          "width":99,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"679de57c502e4a68aea54811becc95d0",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":64,
                      "y":320},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a450716171c4b68b2baffc036d2d09b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":64,
                          "y":320},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"58f6263c162443acb4939497278831ec",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":315},
                    "size":{
                      "width":46,
                      "height":45},
                    "cornerRadiusTopLeft":"43"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"84d4b4b7e5c2450fac0170c08849c13e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":315},
                        "size":{
                          "width":46,
                          "height":45},
                        "cornerRadiusTopLeft":"43"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/个人中心/u7.png"}},
{
                  "id":"d0fe210bae284cfbb3346a6a24f261f0",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "location":{
                      "x":64,
                      "y":340},
                    "size":{
                      "width":140,
                      "height":13}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cf551176d93d47f5bec17879767b2630",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "location":{
                          "x":64,
                          "y":340},
                        "size":{
                          "width":140,
                          "height":13}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"51119288addc4b36a8048d17ead61813",
                  "label":"",
                  "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":173,
                      "y":360},
                    "size":{
                      "width":64,
                      "height":19},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eb43ba618ebc4d2ba09e0061542bb959",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"20862f026fe54c7e8cc438bfab561e13",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":173,
                          "y":360},
                        "size":{
                          "width":64,
                          "height":19},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 链接",
                              "target":{
                                "targetType":"page",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/玩红包/u34.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"1ccb84713a1d491b96862186faf1beaf",
          "label":"顶部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":40,
              "y":80},
            "size":{
              "width":250,
              "height":20},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dee70deb408484b822721c7dc170669",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":40,
                  "y":80},
                "size":{
                  "width":250,
                  "height":20},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/顶部_u80.png"}},
{
          "id":"47fa72f76dc94e2285606d6b63b8dfd3",
          "label":"D",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":530},
            "size":{
              "width":356,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c4e570237c6444f8d1af81b767eee9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":530},
                "size":{
                  "width":356,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u82.png"}},
{
          "id":"c015e55594634d04a5ae937567f04290",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":2},
            "size":{
              "width":327,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e777dd8bbe704135a3780122853a11da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":2},
                "size":{
                  "width":327,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u84.png"}}]}},
  "masters":{
    "93fd5d385bb2419698ca8d204db6bd4a":{
      "packageId":"93fd5d385bb2419698ca8d204db6bd4a",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2e194cf0c2b54c5680885a8df07da4e2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":336,
                "height":627}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0c76e3d052f04fcfb070a80a46e1e3f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":336,
                    "height":627}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u1.png"}},
{
            "id":"12b733eb02494e5a8662e96bcc215f5f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":100},
              "size":{
                "width":250,
                "height":430}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18c2b83789bc48f89e71a44ca19cb8ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":100},
                  "size":{
                    "width":250,
                    "height":430}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u3.png"}}]}}},
  "objectPaths":{
    "fad67a6ec4b544d995743916a3e4eb95":{
      "scriptId":"u0",
      "2e194cf0c2b54c5680885a8df07da4e2":{
        "scriptId":"u1"},
      "0c76e3d052f04fcfb070a80a46e1e3f9":{
        "scriptId":"u2"},
      "12b733eb02494e5a8662e96bcc215f5f":{
        "scriptId":"u3"},
      "18c2b83789bc48f89e71a44ca19cb8ae":{
        "scriptId":"u4"}},
    "20862f026fe54c7e8cc438bfab561e13":{
      "scriptId":"u5"},
    "ca2dc3869f3e4c3a9bff0fa93b1bada3":{
      "scriptId":"u6"},
    "f7a6cef7679f4253bb9233710bcfee4f":{
      "scriptId":"u7"},
    "7078c0bd8fb54032810233af126a87ca":{
      "scriptId":"u8"},
    "f081b9bc693243139cf54bf03fff1734":{
      "scriptId":"u9"},
    "673c0f8ed1684736b37aa2447964ebc6":{
      "scriptId":"u10"},
    "b1d745118c3945b0a3417207742bbd6e":{
      "scriptId":"u11"},
    "27aeb78edcda494db6a710a50da7204d":{
      "scriptId":"u12"},
    "91a21a32469f4f529af0cd0f87b850e8":{
      "scriptId":"u13"},
    "84e3c23849ae4bb08a2458f17930e02d":{
      "scriptId":"u14"},
    "c62c260173dc4d74aa12c01906d004f0":{
      "scriptId":"u15"},
    "41374a28f13f498283551cefb40f2b7e":{
      "scriptId":"u16"},
    "3ab118e0f329426ab74c13612c28d76c":{
      "scriptId":"u17"},
    "4e09ebf2318b4eb389a775d60d8bbfa9":{
      "scriptId":"u18"},
    "12b9918dc9bc477b89c7e591ff3e8f1a":{
      "scriptId":"u19"},
    "33e661b07fae4091b023011ecd6dc03d":{
      "scriptId":"u20"},
    "6180e6d1954f4d99b022ac35acebcc6c":{
      "scriptId":"u21"},
    "8c857627fc204158a96456e18f83c70e":{
      "scriptId":"u22"},
    "fd05ad47a7ff4f9aa40d6aa5aa6eb630":{
      "scriptId":"u23"},
    "0d969cf94b324ca9a4b749fb8bc8e864":{
      "scriptId":"u24"},
    "1db295b409d2412abdbd53caad7443cb":{
      "scriptId":"u25"},
    "92e1308dea184e129f24b1e4a311b4b1":{
      "scriptId":"u26"},
    "a4b5d78d790b40d08f2075e53577d3ee":{
      "scriptId":"u27"},
    "d319c85582a44abd947b7b59a151c232":{
      "scriptId":"u28"},
    "dae314e7cab5462792022f3f4e924b58":{
      "scriptId":"u29"},
    "a79639fa63eb4e62935dee445928e38d":{
      "scriptId":"u30"},
    "bd1308f1768e4c749af3637f54465cce":{
      "scriptId":"u31"},
    "11fa806876124ff5aaeb409b3c614315":{
      "scriptId":"u32"},
    "e8a09a39b981428a9a4b84aa10c70b60":{
      "scriptId":"u33"},
    "82dd593e71ea4a03b302427ee67cb413":{
      "scriptId":"u34"},
    "331e1daea782483484557b12f1083f28":{
      "scriptId":"u35"},
    "0508289cd85b45b4bf1d6d12f7bde3d4":{
      "scriptId":"u36"},
    "2fc6e6b69ab044c8b3bb9030792bcea0":{
      "scriptId":"u37"},
    "b93c9e1951be4c5d81bdadab44c16f7a":{
      "scriptId":"u38"},
    "9efa07ce3b934a8cacb8e23e4b8f7ca0":{
      "scriptId":"u39"},
    "729bcb9523e64b7b9a8a6bbb2ca35c6f":{
      "scriptId":"u40"},
    "407411a9f04943f587f6e9673b4896d2":{
      "scriptId":"u41"},
    "caf640d54be144599956c961aa641af2":{
      "scriptId":"u42"},
    "aa6be57a423241408e39a064890b6be0":{
      "scriptId":"u43"},
    "48541a205f034c11906619f59a7fe776":{
      "scriptId":"u44"},
    "9a728ae7052b4fd48fb7db81d954c5de":{
      "scriptId":"u45"},
    "f6064edb37cd4708a8949e241caf8ad2":{
      "scriptId":"u46"},
    "f4ed28e5b74f45d2906b9102c5fa8e36":{
      "scriptId":"u47"},
    "7a5ecede76d34aefa676f6a7173e076a":{
      "scriptId":"u48"},
    "445cb227994c4ca084a45f7ae035e4db":{
      "scriptId":"u49"},
    "6daaef33b88b426fb1873c6df4508564":{
      "scriptId":"u50"},
    "ab8fac21562b4a4abc79899902eef327":{
      "scriptId":"u51"},
    "679de57c502e4a68aea54811becc95d0":{
      "scriptId":"u52"},
    "6a450716171c4b68b2baffc036d2d09b":{
      "scriptId":"u53"},
    "58f6263c162443acb4939497278831ec":{
      "scriptId":"u54"},
    "84d4b4b7e5c2450fac0170c08849c13e":{
      "scriptId":"u55"},
    "d0fe210bae284cfbb3346a6a24f261f0":{
      "scriptId":"u56"},
    "cf551176d93d47f5bec17879767b2630":{
      "scriptId":"u57"},
    "51119288addc4b36a8048d17ead61813":{
      "scriptId":"u58"},
    "eb43ba618ebc4d2ba09e0061542bb959":{
      "scriptId":"u59"},
    "1ccb84713a1d491b96862186faf1beaf":{
      "scriptId":"u60"},
    "9dee70deb408484b822721c7dc170669":{
      "scriptId":"u61"},
    "47fa72f76dc94e2285606d6b63b8dfd3":{
      "scriptId":"u62"},
    "3c4e570237c6444f8d1af81b767eee9d":{
      "scriptId":"u63"},
    "c015e55594634d04a5ae937567f04290":{
      "scriptId":"u64"},
    "e777dd8bbe704135a3780122853a11da":{
      "scriptId":"u65"}}});