$axure.loadCurrentPage({
  "url":"商品页面2.html",
  "generationDate":new Date(1448007539836.2),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"bohao"],
  "page":{
    "packageId":"39dbd8691e444aa28652add0f8f9c97a",
    "type":"Axure:Page",
    "name":"商品页面2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"12b117f8f1ee445da29eee1818bd0630",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"93fd5d385bb2419698ca8d204db6bd4a"},
{
          "id":"7a7404e7332e4cc09c99ea1fb38e6de8",
          "label":"shangping",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":250,
              "height":430}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"拖动限制<br> (If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 shangping 纵向拖动",
                      "objectsToMoves":[{
                          "objectPath":["7a7404e7332e4cc09c99ea1fb38e6de8"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]},
{
                  "description":"向下拖动<br> (If area of shangping 未接触 area of 顶部1)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["7a7404e7332e4cc09c99ea1fb38e6de8"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["1be38153bc70486daf719908aaaf00d7"]}]}]},
                  "actions":[{
                      "action":"wait",
                      "description":"等待50毫秒",
                      "waitTime":50},
{
                      "action":"moveWidget",
                      "description":"移动 shangping 到 (40,100)",
                      "objectsToMoves":[{
                          "objectPath":["7a7404e7332e4cc09c99ea1fb38e6de8"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"40",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"100",
                              "stos":[]},
                            "options":{
}}}]}]},
{
                  "description":"向上拖动<br> (If area of shangping 未接触 area of 底部1)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["7a7404e7332e4cc09c99ea1fb38e6de8"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["5a79d371bc3343359eaafe776fc2a49d"]}]}]},
                  "actions":[{
                      "action":"wait",
                      "description":"等待50毫秒",
                      "waitTime":50},
{
                      "action":"moveWidget",
                      "description":"移动 shangping 到 (40,60)",
                      "objectsToMoves":[{
                          "objectPath":["7a7404e7332e4cc09c99ea1fb38e6de8"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"40",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"60",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"478e309207574413be0ce3fcb052df38",
              "label":"商品页",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f73c64fd37104dc6ab5ae35dad846d80",
                  "label":"",
                  "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":250,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"76a8cb681be54e278ebffb9b047b1a72",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":250,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品页面2/u6.png"}},
{
                  "id":"c761f45c4e16488f82a9fac05039e6b7",
                  "label":"",
                  "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88.5,
                      "y":43},
                    "size":{
                      "width":73,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a2ba8995d15a45bbad932fcdcd725079",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88.5,
                          "y":43},
                        "size":{
                          "width":73,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"129916fd8f034bbfb936528bf8b2b09e",
                  "label":"",
                  "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":108,
                      "y":71},
                    "size":{
                      "width":34,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f8ea133a6c924c28ad8518e2031f8e3b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":108,
                          "y":71},
                        "size":{
                          "width":34,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d1bbda3e545c4824a8c0feaaa7903d5c",
                  "label":"",
                  "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":10,
                      "y":110},
                    "size":{
                      "width":57,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1d8b0f6dfb68409ea7a279376cb711d1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":10,
                          "y":110},
                        "size":{
                          "width":57,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b1c065177c244110923e84495e7595c9",
                  "label":"",
                  "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":136},
                    "size":{
                      "width":112,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"21a3c8354b4f476e8f696e62da4b0768",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":136},
                        "size":{
                          "width":112,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1f0b249503f44b039a941ad05e6aab95",
                  "label":"",
                  "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":162},
                    "size":{
                      "width":250,
                      "height":48},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"06ce3efc4e614346b0ecac3da34a302b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":162},
                        "size":{
                          "width":250,
                          "height":48},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/商品页面2/u16.png"}},
{
                  "id":"5e9a77e6bc3a41568123523c7fe11259",
                  "label":"",
                  "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":170},
                    "size":{
                      "width":67,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6f68d4e560e44baea7d98bfba44b3d00",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":170},
                        "size":{
                          "width":67,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"413792ba7c8f40689eb1729bd3d954e1",
                  "label":"",
                  "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":192},
                    "size":{
                      "width":60,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a888e873a0a46cb856c2c902447f542",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":192},
                        "size":{
                          "width":60,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b25a34e4823a4b528b3241705ced2c8a",
                  "label":"SP",
                  "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":230},
                    "size":{
                      "width":250,
                      "height":200}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"97be0e18dd7341518875637a05cc06f9",
                      "label":"商品介绍",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"c5a881a478b741cdbab7f745919de733",
                          "label":"",
                          "parentDynamicPanel":"b25a34e4823a4b528b3241705ced2c8a",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFF0000,
                              "opacity":1},
                            "size":{
                              "width":125,
                              "height":40}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"3c2105055023481aa9444f0ed613eed9",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b25a34e4823a4b528b3241705ced2c8a",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFF0000,
                                  "opacity":1},
                                "size":{
                                  "width":125,
                                  "height":40}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"设置 SP to 商品介绍",
                                      "panelsToStates":[{
                                          "panelPath":["b25a34e4823a4b528b3241705ced2c8a"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":1,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":false,
                                            "showWhenSet":false,
                                            "options":{
                                              "compress":false}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/商品页面2/u23.png"}},
{
                          "id":"27c61e1ead2b4e3a856056cde62aa9a6",
                          "label":"",
                          "parentDynamicPanel":"b25a34e4823a4b528b3241705ced2c8a",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":125,
                              "y":0},
                            "size":{
                              "width":125,
                              "height":40}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"14db2623f5ed4e53acd9b114c5088986",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b25a34e4823a4b528b3241705ced2c8a",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":125,
                                  "y":0},
                                "size":{
                                  "width":125,
                                  "height":40}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"设置 SP to 商品介绍",
                                      "panelsToStates":[{
                                          "panelPath":["b25a34e4823a4b528b3241705ced2c8a"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":1,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":false,
                                            "showWhenSet":false,
                                            "options":{
                                              "compress":false}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/商品页面2/u25.png"}},
{
                          "id":"4778282612d84b7eb84c3a9791949763",
                          "label":"",
                          "parentDynamicPanel":"b25a34e4823a4b528b3241705ced2c8a",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":16,
                              "y":56},
                            "size":{
                              "width":210,
                              "height":114}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"db3eb70b6e13406da2f17f71da5b32fe",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b25a34e4823a4b528b3241705ced2c8a",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":16,
                                  "y":56},
                                "size":{
                                  "width":210,
                                  "height":114}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}},
{
                      "id":"1c44f749e8dc4b34b7b2a11f2b06e387",
                      "label":"商品承诺书",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"40c33181283d4754a19dcb5df6c2f422",
                          "label":"",
                          "parentDynamicPanel":"b25a34e4823a4b528b3241705ced2c8a",
                          "panelIndex":1,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF000000,
                              "opacity":1},
                            "size":{
                              "width":125,
                              "height":40}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"463a04fd697b4a36b335ed93433f0842",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b25a34e4823a4b528b3241705ced2c8a",
                              "panelIndex":1,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF000000,
                                  "opacity":1},
                                "size":{
                                  "width":125,
                                  "height":40}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"设置 SP to 商品介绍",
                                      "panelsToStates":[{
                                          "panelPath":["b25a34e4823a4b528b3241705ced2c8a"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":1,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":false,
                                            "showWhenSet":false,
                                            "options":{
                                              "compress":false}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/商品页面2/u25.png"}},
{
                          "id":"d3febeec08294a85924f93e1e992b7e4",
                          "label":"",
                          "parentDynamicPanel":"b25a34e4823a4b528b3241705ced2c8a",
                          "panelIndex":1,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFF0000,
                              "opacity":1},
                            "location":{
                              "x":125,
                              "y":0},
                            "size":{
                              "width":125,
                              "height":40}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"5948c28a924c45bfaaee889278e6b3f6",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b25a34e4823a4b528b3241705ced2c8a",
                              "panelIndex":1,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFFFF0000,
                                  "opacity":1},
                                "location":{
                                  "x":125,
                                  "y":0},
                                "size":{
                                  "width":125,
                                  "height":40}},
                              "adaptiveStyles":{
}}],
                          "interactionMap":{
                            "onClick":{
                              "description":"OnClick",
                              "cases":[{
                                  "description":"用例 1",
                                  "isNewIfGroup":false,
                                  "actions":[{
                                      "action":"setPanelState",
                                      "description":"设置 SP to 商品承诺书",
                                      "panelsToStates":[{
                                          "panelPath":["b25a34e4823a4b528b3241705ced2c8a"],
                                          "stateInfo":{
                                            "setStateType":"diagram",
                                            "stateNumber":2,
                                            "stateValue":{
                                              "exprType":"stringLiteral",
                                              "value":"1",
                                              "stos":[]},
                                            "loop":false,
                                            "showWhenSet":false,
                                            "options":{
                                              "compress":false}}}]}]}]}},
                          "tabbable":true,
                          "images":{
                            "normal~":"images/商品页面2/u23.png"}},
{
                          "id":"baf5912c06254831919088ccb2502085",
                          "label":"",
                          "parentDynamicPanel":"b25a34e4823a4b528b3241705ced2c8a",
                          "panelIndex":1,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":200,
                              "height":120}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"9b65ca1ec69745b7a0443fc2e12cffab",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"b25a34e4823a4b528b3241705ced2c8a",
                              "panelIndex":1,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":20,
                                  "y":60},
                                "size":{
                                  "width":200,
                                  "height":120}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/商品页面2/u33.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"030f3865f75f40479abe5b4f1a895a24",
                  "label":"",
                  "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f36328a625f2484fb8864ace1b9ee880",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"ba7f5e17ecbb42a7b05dd87e024e1d57",
                  "label":"",
                  "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":98,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"700348034e4049609fdd90adb4426ad8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":98,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fef19be1d8074a9aa75346032ae9bace",
                  "label":"",
                  "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":7},
                    "size":{
                      "width":35,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c4898c8802e949a78cc8961529da9826",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7a7404e7332e4cc09c99ea1fb38e6de8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":7},
                        "size":{
                          "width":35,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"5a79d371bc3343359eaafe776fc2a49d",
          "label":"底部1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":490},
            "size":{
              "width":250,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"091e62e8491e40578cd6785d78646c96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":490},
                "size":{
                  "width":250,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/底部1_u88.png"}},
{
          "id":"1be38153bc70486daf719908aaaf00d7",
          "label":"顶部1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":40,
              "y":80},
            "size":{
              "width":250,
              "height":20},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccf3e466648e449c9539679e877265ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":40,
                  "y":80},
                "size":{
                  "width":250,
                  "height":20},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/顶部_u80.png"}},
{
          "id":"23178980de4a46b58a0870848fbcf2dd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":5},
            "size":{
              "width":327,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13f44206af374d3f8874fea632689a83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":5},
                "size":{
                  "width":327,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u84.png"}},
{
          "id":"b28043bd12c44d23baae461eda326214",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":495},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"768d841b654e4b528a6d86ac452ff462",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":495},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 兑换页面",
                      "target":{
                        "targetType":"page",
                        "url":"兑换页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商品页面2/u47.png"}}]}},
  "masters":{
    "93fd5d385bb2419698ca8d204db6bd4a":{
      "packageId":"93fd5d385bb2419698ca8d204db6bd4a",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2e194cf0c2b54c5680885a8df07da4e2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":336,
                "height":627}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0c76e3d052f04fcfb070a80a46e1e3f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":336,
                    "height":627}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u1.png"}},
{
            "id":"12b733eb02494e5a8662e96bcc215f5f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":100},
              "size":{
                "width":250,
                "height":430}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18c2b83789bc48f89e71a44ca19cb8ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":100},
                  "size":{
                    "width":250,
                    "height":430}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u3.png"}}]}}},
  "objectPaths":{
    "12b117f8f1ee445da29eee1818bd0630":{
      "scriptId":"u0",
      "2e194cf0c2b54c5680885a8df07da4e2":{
        "scriptId":"u1"},
      "0c76e3d052f04fcfb070a80a46e1e3f9":{
        "scriptId":"u2"},
      "12b733eb02494e5a8662e96bcc215f5f":{
        "scriptId":"u3"},
      "18c2b83789bc48f89e71a44ca19cb8ae":{
        "scriptId":"u4"}},
    "7a7404e7332e4cc09c99ea1fb38e6de8":{
      "scriptId":"u5"},
    "f73c64fd37104dc6ab5ae35dad846d80":{
      "scriptId":"u6"},
    "76a8cb681be54e278ebffb9b047b1a72":{
      "scriptId":"u7"},
    "c761f45c4e16488f82a9fac05039e6b7":{
      "scriptId":"u8"},
    "a2ba8995d15a45bbad932fcdcd725079":{
      "scriptId":"u9"},
    "129916fd8f034bbfb936528bf8b2b09e":{
      "scriptId":"u10"},
    "f8ea133a6c924c28ad8518e2031f8e3b":{
      "scriptId":"u11"},
    "d1bbda3e545c4824a8c0feaaa7903d5c":{
      "scriptId":"u12"},
    "1d8b0f6dfb68409ea7a279376cb711d1":{
      "scriptId":"u13"},
    "b1c065177c244110923e84495e7595c9":{
      "scriptId":"u14"},
    "21a3c8354b4f476e8f696e62da4b0768":{
      "scriptId":"u15"},
    "1f0b249503f44b039a941ad05e6aab95":{
      "scriptId":"u16"},
    "06ce3efc4e614346b0ecac3da34a302b":{
      "scriptId":"u17"},
    "5e9a77e6bc3a41568123523c7fe11259":{
      "scriptId":"u18"},
    "6f68d4e560e44baea7d98bfba44b3d00":{
      "scriptId":"u19"},
    "413792ba7c8f40689eb1729bd3d954e1":{
      "scriptId":"u20"},
    "6a888e873a0a46cb856c2c902447f542":{
      "scriptId":"u21"},
    "b25a34e4823a4b528b3241705ced2c8a":{
      "scriptId":"u22"},
    "c5a881a478b741cdbab7f745919de733":{
      "scriptId":"u23"},
    "3c2105055023481aa9444f0ed613eed9":{
      "scriptId":"u24"},
    "27c61e1ead2b4e3a856056cde62aa9a6":{
      "scriptId":"u25"},
    "14db2623f5ed4e53acd9b114c5088986":{
      "scriptId":"u26"},
    "4778282612d84b7eb84c3a9791949763":{
      "scriptId":"u27"},
    "db3eb70b6e13406da2f17f71da5b32fe":{
      "scriptId":"u28"},
    "40c33181283d4754a19dcb5df6c2f422":{
      "scriptId":"u29"},
    "463a04fd697b4a36b335ed93433f0842":{
      "scriptId":"u30"},
    "d3febeec08294a85924f93e1e992b7e4":{
      "scriptId":"u31"},
    "5948c28a924c45bfaaee889278e6b3f6":{
      "scriptId":"u32"},
    "baf5912c06254831919088ccb2502085":{
      "scriptId":"u33"},
    "9b65ca1ec69745b7a0443fc2e12cffab":{
      "scriptId":"u34"},
    "030f3865f75f40479abe5b4f1a895a24":{
      "scriptId":"u35"},
    "f36328a625f2484fb8864ace1b9ee880":{
      "scriptId":"u36"},
    "ba7f5e17ecbb42a7b05dd87e024e1d57":{
      "scriptId":"u37"},
    "700348034e4049609fdd90adb4426ad8":{
      "scriptId":"u38"},
    "fef19be1d8074a9aa75346032ae9bace":{
      "scriptId":"u39"},
    "c4898c8802e949a78cc8961529da9826":{
      "scriptId":"u40"},
    "5a79d371bc3343359eaafe776fc2a49d":{
      "scriptId":"u41"},
    "091e62e8491e40578cd6785d78646c96":{
      "scriptId":"u42"},
    "1be38153bc70486daf719908aaaf00d7":{
      "scriptId":"u43"},
    "ccf3e466648e449c9539679e877265ff":{
      "scriptId":"u44"},
    "23178980de4a46b58a0870848fbcf2dd":{
      "scriptId":"u45"},
    "13f44206af374d3f8874fea632689a83":{
      "scriptId":"u46"},
    "b28043bd12c44d23baae461eda326214":{
      "scriptId":"u47"},
    "768d841b654e4b528a6d86ac452ff462":{
      "scriptId":"u48"}}});