$axure.loadCurrentPage({
  "url":"消息中心.html",
  "generationDate":new Date(1448007540470.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"bohao"],
  "page":{
    "packageId":"5f3bfa0e2a0a40d28074c4a9b12e1b2c",
    "type":"Axure:Page",
    "name":"消息中心",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7cc08ce7eb914c22b1696e3c3f19082d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"93fd5d385bb2419698ca8d204db6bd4a"},
{
          "id":"0b8a8a8c2504411a82fb84dbfc97480f",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":250,
              "height":430}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b4d8f9506d634e8fad6c36cd32b275d3",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"dd8975bcc9c44282b4b7e23b64239f4c",
                  "label":"",
                  "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bb2acd7191b24d1eb9b6852837f2276b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"2a5d898db6f94ef0b3616f4c73ad78ed",
                  "label":"",
                  "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":98,
                      "y":7},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"596d19adf9934e61887fa6067ecfaf9d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":98,
                          "y":7},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9386528ae5fe4b9fa6c7ec50a34b5f78",
                  "label":"",
                  "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":7},
                    "size":{
                      "width":35,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"305d331790654491892f1c13612b3367",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":7},
                        "size":{
                          "width":35,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"Set Panel to State",
                              "panelsToStates":[]},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"adccd4e9adab404fa3268004e7ff61f7",
                  "label":"",
                  "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":42},
                    "size":{
                      "width":35,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b08dd7786006436f9f3095d55daab037",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":42},
                        "size":{
                          "width":35,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/消息中心/u12.png"}},
{
                  "id":"6d0b70f962ad49fa8ee76b46eef017da",
                  "label":"",
                  "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":53,
                      "y":40},
                    "size":{
                      "width":92,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9fc9123cf79a4c2aa7db76c830b73b18",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":53,
                          "y":40},
                        "size":{
                          "width":92,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c63b6eeec4bf421285830439d563ffa3",
                  "label":"",
                  "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"11px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":53,
                      "y":59},
                    "size":{
                      "width":188,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"94f2261b56a846529146e9d0dc1f3b66",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"11px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":53,
                          "y":59},
                        "size":{
                          "width":188,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8130fd8c121b49a8a5d1592e29c610d7",
                  "label":"",
                  "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":88},
                    "size":{
                      "width":210,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/个人中心/u487_line.png"}},
{
                  "id":"5d29cfcd98ad4e27b5358723966d5961",
                  "label":"",
                  "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":53,
                      "y":76},
                    "size":{
                      "width":39,
                      "height":13}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"299841942e4341b1832f61a816bb1e6a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":53,
                          "y":76},
                        "size":{
                          "width":39,
                          "height":13}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"501f0f37c364475e9e238086dee1eab5",
                  "label":"",
                  "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":110},
                    "size":{
                      "width":35,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"313898fcc86c4673859b40b6c3f759fe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":110},
                        "size":{
                          "width":35,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/消息中心/u12.png"}},
{
                  "id":"57c4f41a9f0f48348752ad71b038fc1c",
                  "label":"",
                  "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":54,
                      "y":108},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b267328ef97244e58f5afab8976b4d2e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":54,
                          "y":108},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6022f589622e4028bde065d9fb501e46",
                  "label":"",
                  "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"11px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":54,
                      "y":127},
                    "size":{
                      "width":143,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aa2b058a25134b269021a9a7a14813ed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"11px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":54,
                          "y":127},
                        "size":{
                          "width":143,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0dd275635af4446a8fbef2707fc8bbb1",
                  "label":"",
                  "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20.5,
                      "y":156},
                    "size":{
                      "width":210,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/个人中心/u487_line.png"}},
{
                  "id":"c670278dc3404bd986e299057c4c57f7",
                  "label":"",
                  "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":54,
                      "y":144},
                    "size":{
                      "width":39,
                      "height":13}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"af2d8c9cbca54c4fa65e79aadbfb3626",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0b8a8a8c2504411a82fb84dbfc97480f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"10px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":54,
                          "y":144},
                        "size":{
                          "width":39,
                          "height":13}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "93fd5d385bb2419698ca8d204db6bd4a":{
      "packageId":"93fd5d385bb2419698ca8d204db6bd4a",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2e194cf0c2b54c5680885a8df07da4e2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":336,
                "height":627}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0c76e3d052f04fcfb070a80a46e1e3f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":336,
                    "height":627}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u1.png"}},
{
            "id":"12b733eb02494e5a8662e96bcc215f5f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":100},
              "size":{
                "width":250,
                "height":430}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18c2b83789bc48f89e71a44ca19cb8ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":100},
                  "size":{
                    "width":250,
                    "height":430}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u3.png"}}]}}},
  "objectPaths":{
    "7cc08ce7eb914c22b1696e3c3f19082d":{
      "scriptId":"u0",
      "2e194cf0c2b54c5680885a8df07da4e2":{
        "scriptId":"u1"},
      "0c76e3d052f04fcfb070a80a46e1e3f9":{
        "scriptId":"u2"},
      "12b733eb02494e5a8662e96bcc215f5f":{
        "scriptId":"u3"},
      "18c2b83789bc48f89e71a44ca19cb8ae":{
        "scriptId":"u4"}},
    "0b8a8a8c2504411a82fb84dbfc97480f":{
      "scriptId":"u5"},
    "dd8975bcc9c44282b4b7e23b64239f4c":{
      "scriptId":"u6"},
    "bb2acd7191b24d1eb9b6852837f2276b":{
      "scriptId":"u7"},
    "2a5d898db6f94ef0b3616f4c73ad78ed":{
      "scriptId":"u8"},
    "596d19adf9934e61887fa6067ecfaf9d":{
      "scriptId":"u9"},
    "9386528ae5fe4b9fa6c7ec50a34b5f78":{
      "scriptId":"u10"},
    "305d331790654491892f1c13612b3367":{
      "scriptId":"u11"},
    "adccd4e9adab404fa3268004e7ff61f7":{
      "scriptId":"u12"},
    "b08dd7786006436f9f3095d55daab037":{
      "scriptId":"u13"},
    "6d0b70f962ad49fa8ee76b46eef017da":{
      "scriptId":"u14"},
    "9fc9123cf79a4c2aa7db76c830b73b18":{
      "scriptId":"u15"},
    "c63b6eeec4bf421285830439d563ffa3":{
      "scriptId":"u16"},
    "94f2261b56a846529146e9d0dc1f3b66":{
      "scriptId":"u17"},
    "8130fd8c121b49a8a5d1592e29c610d7":{
      "scriptId":"u18"},
    "5d29cfcd98ad4e27b5358723966d5961":{
      "scriptId":"u19"},
    "299841942e4341b1832f61a816bb1e6a":{
      "scriptId":"u20"},
    "501f0f37c364475e9e238086dee1eab5":{
      "scriptId":"u21"},
    "313898fcc86c4673859b40b6c3f759fe":{
      "scriptId":"u22"},
    "57c4f41a9f0f48348752ad71b038fc1c":{
      "scriptId":"u23"},
    "b267328ef97244e58f5afab8976b4d2e":{
      "scriptId":"u24"},
    "6022f589622e4028bde065d9fb501e46":{
      "scriptId":"u25"},
    "aa2b058a25134b269021a9a7a14813ed":{
      "scriptId":"u26"},
    "0dd275635af4446a8fbef2707fc8bbb1":{
      "scriptId":"u27"},
    "c670278dc3404bd986e299057c4c57f7":{
      "scriptId":"u28"},
    "af2d8c9cbca54c4fa65e79aadbfb3626":{
      "scriptId":"u29"}}});