$axure.loadCurrentPage({
  "url":"广告.html",
  "generationDate":new Date(1448007540877.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"bohao"],
  "page":{
    "packageId":"5c4771dccd99449e86157fc6a5eaca0e",
    "type":"Axure:Page",
    "name":"广告",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9dfb62a2eebd4bb0b6e2ccbec099c0bf",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"93fd5d385bb2419698ca8d204db6bd4a"},
{
          "id":"31783725086c4f8397d21eaa8a45b070",
          "label":"guanggao",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":100},
            "size":{
              "width":250,
              "height":580}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"拖动限制<br> (If True)",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 guanggao 纵向拖动",
                      "objectsToMoves":[{
                          "objectPath":["31783725086c4f8397d21eaa8a45b070"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]},
{
                  "description":"向下拖动<br> (If area of guanggao 未接触 area of 顶部)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["31783725086c4f8397d21eaa8a45b070"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["f37b191ee8854b198ecd8fbec269c24e"]}]}]},
                  "actions":[{
                      "action":"wait",
                      "description":"等待50毫秒",
                      "waitTime":50},
{
                      "action":"moveWidget",
                      "description":"移动 guanggao 到 (40,100)",
                      "objectsToMoves":[{
                          "objectPath":["31783725086c4f8397d21eaa8a45b070"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"40",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"100",
                              "stos":[]},
                            "options":{
}}}]}]},
{
                  "description":"向上拖动<br> (If area of guanggao 未接触 area of 底部)",
                  "isNewIfGroup":true,
                  "condition":{
                    "exprType":"fcall",
                    "functionName":"IsNotOver",
                    "arguments":[{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["31783725086c4f8397d21eaa8a45b070"]}]},
{
                        "exprType":"fcall",
                        "functionName":"GetWidgetRectangles",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":false,
                            "isFocused":false,
                            "isTarget":false,
                            "value":["8cd05ef261fc449ea183802f8fe2424f"]}]}]},
                  "actions":[{
                      "action":"wait",
                      "description":"等待50毫秒",
                      "waitTime":50},
{
                      "action":"moveWidget",
                      "description":"移动 guanggao 到 (40,-40)",
                      "objectsToMoves":[{
                          "objectPath":["31783725086c4f8397d21eaa8a45b070"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"40",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"-40",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"fbaac41f038e41d0b7ccd80f1969d7f9",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bd15ba6efd894072a5299d3b497badcc",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":250,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5bf3052d4ae242209a33be8db69bdb37",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":250,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/捡易币/u12.png"}},
{
                  "id":"0eefa1ee5d8f451398068e016a9c1d73",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":88,
                      "y":66},
                    "size":{
                      "width":73,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cd0688093c45476f8d4b823b7826e556",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":88,
                          "y":66},
                        "size":{
                          "width":73,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"76da5292e9d545d6b6418a7179096d7d",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":18,
                      "y":140},
                    "size":{
                      "width":57,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"691c89dffb9b4150b22764fbdebe654f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":18,
                          "y":140},
                        "size":{
                          "width":57,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bd9ce3bd34b64c40963806eea7141ca5",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":166},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"85b1bd1ab142406b9640e35be1f5e90a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":166},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"63c6a82cb608448b805e48122608776d",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":192},
                    "size":{
                      "width":250,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/index/u36_line.png"}},
{
                  "id":"9c8dfbe119df44318bc68b0b9b71f936",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":156},
                    "size":{
                      "width":200,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF777777}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/广告/u15_line.png"}},
{
                  "id":"26e04c7809d247f7ad1dec87ecb6c109",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":220},
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9ca196d1e8e24031ac6451ba4d3dbada",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":220},
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"8e9e4c4cd79443b4bf77247d52fa30fd",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":228},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"97529c9070174fd1b77f54aa2eddbac8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":228},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8a935717647548f2885d8a343e0d9088",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":260},
                    "size":{
                      "width":250,
                      "height":150}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b311e8d381ec4e04b214712a923b35b6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":260},
                        "size":{
                          "width":250,
                          "height":150}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/广告/u20.png"}},
{
                  "id":"e3d0320a34874cd3a03ea0d0a1d770b7",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":430},
                    "size":{
                      "width":250,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"72cfe9fb463e42bc8d550652a7248c75",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":430},
                        "size":{
                          "width":250,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/广告/u22.png"}},
{
                  "id":"4a72bfc7254540f49f7f11683d54dc5d",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":433},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"260a2b479c954f41a8344cc23fd63a21",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":433},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b2840ece48d447cd94ab896766c2b916",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":18,
                      "y":459},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"43a3640cb29e4132ab130e4fa65f4a56",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":18,
                          "y":459},
                        "size":{
                          "width":30,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/广告/u26.png"}},
{
                  "id":"14daf92a58624ba89f3798ae7eb5d450",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":58,
                      "y":456},
                    "size":{
                      "width":49,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"25caf652dc9a40d386013407195c6e50",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":58,
                          "y":456},
                        "size":{
                          "width":49,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c31cdf7171dc432796862abe49cefe2f",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":58,
                      "y":474},
                    "size":{
                      "width":49,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"60d7e16944194a038bdeca1fcf6de015",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":58,
                          "y":474},
                        "size":{
                          "width":49,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9dbe447d2d7f4a9097ad1e9fbcceffd1",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":25,
                      "y":489},
                    "size":{
                      "width":205,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF777777}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/广告/u32_line.png"}},
{
                  "id":"ebd519ca16ab443f933af9d5fcba8c23",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":18,
                      "y":499},
                    "size":{
                      "width":142,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"630cd7301dbe435ba090b5b00b1ce693",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":18,
                          "y":499},
                        "size":{
                          "width":142,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f3d4c3891fbb4cbf9d2796863d9cc63f",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":538},
                    "size":{
                      "width":250,
                      "height":40}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"def9304fc5a040cf9884d320bb561850",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":538},
                        "size":{
                          "width":250,
                          "height":40}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/底部1_u88.png"}},
{
                  "id":"df0c0cfad99f4d1b8c9cec4ebab55bcd",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":543},
                    "size":{
                      "width":100,
                      "height":30},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"76d7a9502c5644ef969e2b167a5fe022",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":140,
                          "y":543},
                        "size":{
                          "width":100,
                          "height":30},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 +yibi 向上滑动 500 毫秒",
                              "objectsToFades":[{
                                  "objectPath":["669efd2483974c38bcde25f263f69ca3"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "easing":"slideUp",
                                      "duration":500,
                                      "showType":"none"}}}]},
{
                              "action":"wait",
                              "description":"等待700毫秒",
                              "waitTime":700},
{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 捡易币",
                              "target":{
                                "targetType":"page",
                                "url":"捡易币.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/商品页面2/u47.png"}},
{
                  "id":"669efd2483974c38bcde25f263f69ca3",
                  "label":"+yibi",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":false,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":67,
                      "y":372},
                    "size":{
                      "width":116,
                      "height":28},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5ede29904e8243afb05de402d7112904",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":67,
                          "y":372},
                        "size":{
                          "width":116,
                          "height":28},
                        "visible":false},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fdffa92ab11d4987a8c388f9e89a277a",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e277781d1314f168c1c0f1cacbe6ed7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/index/u30.png"}},
{
                  "id":"5f9f44a483b448a4b71851c75b18b8ac",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":98,
                      "y":7},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3962043c4fc34913bde5272eb3fab038",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":98,
                          "y":7},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0f5a414648ce4814852d13790fb7ba6c",
                  "label":"",
                  "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":8,
                      "y":7},
                    "size":{
                      "width":35,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4eba7db435e14051af86b22809d11882",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"31783725086c4f8397d21eaa8a45b070",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":8,
                          "y":7},
                        "size":{
                          "width":35,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 捡易币",
                              "target":{
                                "targetType":"page",
                                "url":"捡易币.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"f37b191ee8854b198ecd8fbec269c24e",
          "label":"顶部",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":40,
              "y":80},
            "size":{
              "width":250,
              "height":20},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f58e7c1ea9504a3a9a6b8f4310e733eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":40,
                  "y":80},
                "size":{
                  "width":250,
                  "height":20},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/顶部_u80.png"}},
{
          "id":"8cd05ef261fc449ea183802f8fe2424f",
          "label":"底部",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":530},
            "size":{
              "width":356,
              "height":276}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f14af2b067124ce695d3134fbff1c608",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":530},
                "size":{
                  "width":356,
                  "height":276}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u82.png"}},
{
          "id":"b866816cf5c2490dafab8c98f4103711",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":3,
              "y":2},
            "size":{
              "width":327,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e568da55d7c430f9476f69865840f53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":3,
                  "y":2},
                "size":{
                  "width":327,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u84.png"}},
{
          "id":"91aa64d3be8b41099009ea362a428256",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":336,
              "height":2},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5533cd9fbea8468f8dcccd152ed4317b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":336,
                  "height":2},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u86.png"}}]}},
  "masters":{
    "93fd5d385bb2419698ca8d204db6bd4a":{
      "packageId":"93fd5d385bb2419698ca8d204db6bd4a",
      "type":"Axure:Master",
      "name":"手机",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"2e194cf0c2b54c5680885a8df07da4e2",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":336,
                "height":627}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0c76e3d052f04fcfb070a80a46e1e3f9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":336,
                    "height":627}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u1.png"}},
{
            "id":"12b733eb02494e5a8662e96bcc215f5f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":100},
              "size":{
                "width":250,
                "height":430}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"18c2b83789bc48f89e71a44ca19cb8ae",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":100},
                  "size":{
                    "width":250,
                    "height":430}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/index/u3.png"}}]}}},
  "objectPaths":{
    "9dfb62a2eebd4bb0b6e2ccbec099c0bf":{
      "scriptId":"u0",
      "2e194cf0c2b54c5680885a8df07da4e2":{
        "scriptId":"u1"},
      "0c76e3d052f04fcfb070a80a46e1e3f9":{
        "scriptId":"u2"},
      "12b733eb02494e5a8662e96bcc215f5f":{
        "scriptId":"u3"},
      "18c2b83789bc48f89e71a44ca19cb8ae":{
        "scriptId":"u4"}},
    "31783725086c4f8397d21eaa8a45b070":{
      "scriptId":"u5"},
    "bd15ba6efd894072a5299d3b497badcc":{
      "scriptId":"u6"},
    "5bf3052d4ae242209a33be8db69bdb37":{
      "scriptId":"u7"},
    "0eefa1ee5d8f451398068e016a9c1d73":{
      "scriptId":"u8"},
    "cd0688093c45476f8d4b823b7826e556":{
      "scriptId":"u9"},
    "76da5292e9d545d6b6418a7179096d7d":{
      "scriptId":"u10"},
    "691c89dffb9b4150b22764fbdebe654f":{
      "scriptId":"u11"},
    "bd9ce3bd34b64c40963806eea7141ca5":{
      "scriptId":"u12"},
    "85b1bd1ab142406b9640e35be1f5e90a":{
      "scriptId":"u13"},
    "63c6a82cb608448b805e48122608776d":{
      "scriptId":"u14"},
    "9c8dfbe119df44318bc68b0b9b71f936":{
      "scriptId":"u15"},
    "26e04c7809d247f7ad1dec87ecb6c109":{
      "scriptId":"u16"},
    "9ca196d1e8e24031ac6451ba4d3dbada":{
      "scriptId":"u17"},
    "8e9e4c4cd79443b4bf77247d52fa30fd":{
      "scriptId":"u18"},
    "97529c9070174fd1b77f54aa2eddbac8":{
      "scriptId":"u19"},
    "8a935717647548f2885d8a343e0d9088":{
      "scriptId":"u20"},
    "b311e8d381ec4e04b214712a923b35b6":{
      "scriptId":"u21"},
    "e3d0320a34874cd3a03ea0d0a1d770b7":{
      "scriptId":"u22"},
    "72cfe9fb463e42bc8d550652a7248c75":{
      "scriptId":"u23"},
    "4a72bfc7254540f49f7f11683d54dc5d":{
      "scriptId":"u24"},
    "260a2b479c954f41a8344cc23fd63a21":{
      "scriptId":"u25"},
    "b2840ece48d447cd94ab896766c2b916":{
      "scriptId":"u26"},
    "43a3640cb29e4132ab130e4fa65f4a56":{
      "scriptId":"u27"},
    "14daf92a58624ba89f3798ae7eb5d450":{
      "scriptId":"u28"},
    "25caf652dc9a40d386013407195c6e50":{
      "scriptId":"u29"},
    "c31cdf7171dc432796862abe49cefe2f":{
      "scriptId":"u30"},
    "60d7e16944194a038bdeca1fcf6de015":{
      "scriptId":"u31"},
    "9dbe447d2d7f4a9097ad1e9fbcceffd1":{
      "scriptId":"u32"},
    "ebd519ca16ab443f933af9d5fcba8c23":{
      "scriptId":"u33"},
    "630cd7301dbe435ba090b5b00b1ce693":{
      "scriptId":"u34"},
    "f3d4c3891fbb4cbf9d2796863d9cc63f":{
      "scriptId":"u35"},
    "def9304fc5a040cf9884d320bb561850":{
      "scriptId":"u36"},
    "df0c0cfad99f4d1b8c9cec4ebab55bcd":{
      "scriptId":"u37"},
    "76d7a9502c5644ef969e2b167a5fe022":{
      "scriptId":"u38"},
    "669efd2483974c38bcde25f263f69ca3":{
      "scriptId":"u39"},
    "5ede29904e8243afb05de402d7112904":{
      "scriptId":"u40"},
    "fdffa92ab11d4987a8c388f9e89a277a":{
      "scriptId":"u41"},
    "7e277781d1314f168c1c0f1cacbe6ed7":{
      "scriptId":"u42"},
    "5f9f44a483b448a4b71851c75b18b8ac":{
      "scriptId":"u43"},
    "3962043c4fc34913bde5272eb3fab038":{
      "scriptId":"u44"},
    "0f5a414648ce4814852d13790fb7ba6c":{
      "scriptId":"u45"},
    "4eba7db435e14051af86b22809d11882":{
      "scriptId":"u46"},
    "f37b191ee8854b198ecd8fbec269c24e":{
      "scriptId":"u47"},
    "f58e7c1ea9504a3a9a6b8f4310e733eb":{
      "scriptId":"u48"},
    "8cd05ef261fc449ea183802f8fe2424f":{
      "scriptId":"u49"},
    "f14af2b067124ce695d3134fbff1c608":{
      "scriptId":"u50"},
    "b866816cf5c2490dafab8c98f4103711":{
      "scriptId":"u51"},
    "5e568da55d7c430f9476f69865840f53":{
      "scriptId":"u52"},
    "91aa64d3be8b41099009ea362a428256":{
      "scriptId":"u53"},
    "5533cd9fbea8468f8dcccd152ed4317b":{
      "scriptId":"u54"}}});